### ISSUE TITLE
[Badcase]: 使用Qwen2-7b翻译中文，有额外的输出

### ISSUE THREAD

**Issue by cjjjy** [QwenLM/Qwen2.5#1005]
### Model Series

Qwen2

### What are the models used?

Qwen2-7B

### What is the scenario where the problem happened?

使用Qwen2-7B进行翻译文本，回复答案总是出现额外的数学推理的文本，

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

OS: Ubuntu 22.04
Python: Python 3.11
GPUs: GTX3090
NVIDIA driver: 535 (from nvidia-smi)
CUDA compiler: 12.1 (from nvcc -V)
PyTorch: 2.4.1+cu121 

#### Steps to reproduce

This happens to Qwen2.5-7B
The badcase can be reproduced as follows:
![image](https://github.com/user-attachments/assets/044e6fd5-8e4a-418f-a536-bfc5d8dec291)

![image](https://github.com/user-attachments/assets/661c7f2a-8b4a-4822-960c-94a16b4e50ac)

**Comment by jklj077** [comment]
use instruct
