### ISSUE TITLE
[Bug]: Qwen 2.5 tool calls change function names after response

### ISSUE THREAD

**Issue by LuckLittleBoy** [QwenLM/Qwen2.5#1012]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-7B-Instruct

### What is the scenario where the problem happened?

deployment with vllm, tool calling with ollama

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

OS: Linux
Python: 3.10.12
PyTorch: 2.4.0+cpu
vLLM: v0.6.1.post2
Ollama: 0.3.10

### Log output

```shell
request tool function name is cInBMXzQGq58, but response tool function name changed to cInBMXzQz58
```

#### Ollama

ollama request:

curl http://localhost:11434/v1/chat/completions -d '{
"model": "qwen2.5",
"temperature": 0.01,
"max_tokens": 2000,
"stream": false,
"messages": [
{
"role": "user",
"content": "系统状态"
}
],
"tools": [
{
"type": "function",
"function": {
"name": "cInBMXzQGq58",
"description": "系统状态方面",
"parameters": {
"type": "object",
"properties": {},
"required": []
}
}
}
],
"tool_choice": "auto"
}'

ollama response:

{
"id": "chatcmpl-724",
"object": "chat.completion",
"created": 1728697253,
"model": "qwen2.5",
"system_fingerprint": "fp_ollama",
"choices": [
{
"index": 0,
"message": {
"role": "assistant",
"content": "",
"tool_calls": [
{
"id": "call_l565rajv",
"type": "function",
"function": {
"name": "cInBMXzQz58",
"arguments": "{}"
}
}
]
},
"finish_reason": "tool_calls"
}
],
"usage": {
"prompt_tokens": 151,
"completion_tokens": 23,
"total_tokens": 174
}
}

#### vLLM

vLLM request: 

![image](https://github.com/user-attachments/assets/70d12459-7695-466f-8069-d69b18a2a02e)

vLLM response:

![image](https://github.com/user-attachments/assets/0961f773-e365-4cd0-954b-41e94db92dc4)

**Comment by LuckLittleBoy** [comment]
@JianxinMa 这是不是模型的问题

**Comment by jklj077** [comment]
why this name?

**Comment by LuckLittleBoy** [comment]
> why this name?

A random ID generated in the fastgpt program. qwen2 does not have this issue
