### ISSUE TITLE
[Bug]: No heartbeat received from MQLLMEngine

### ISSUE THREAD

**Issue by hulk-zhk** [QwenLM/Qwen2.5#1013]
### Model Series

Qwen1.5

### What are the models used?

qwen1.5-4b

### What is the scenario where the problem happened?

进行推理时报的错误

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

PyTorch version: 2.4.0+cu121
Python version: 3.10.12
Ubuntu 22.04.4

### Log output

```shell
No heartbeat received from MQLLMEngine
```

### Description

启动模型服务：
python3 -m vllm.entrypoints.openai.api_server --host [0.0.0.0](http://0.0.0.0/) \
--port 10023 --seed 1024 \
--served-model qwen1.5-4b \
--model "/home/work/ssd1/Qwen1.5-4B-Chat" --trust-remote-code \
--tokenizer-mode slow --max-model-len 128 \
--dtype float16 
进行模型推理：
curl http://127.0.0.1:10023/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model":"qwen1.5-4b", "max_tokens":64, "seed":0, "top_k":1, "top_p":0.8, "temperature":0.3, 
"prompt": "谈谈你对大模型的理解"
}'
报错信息：
No heartbeat received from MQLLMEngine

**Comment by jklj077** [comment]
seems that something is running really slow and blocking the vllm main thread; see similar issues at https://github.com/vllm-project/vllm/issues/9082
