### ISSUE TITLE
[Badcase]: 相同的微调数据，Qwen1.5 14B准确率比Qwen2.5 14B高20%左右，这是什么原因

### ISSUE THREAD

**Issue by Jayc-Z** [QwenLM/Qwen2.5#1016]
### Model Series

Qwen2.5

### What are the models used?

qwen2.5-14B-Instruct

### What is the scenario where the problem happened?

Qwen2.5-14B-Instruct LoRA微调效果不好

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

任务简介：判断query的最小时间单位，方便环比同比的时间推理
例：
query：我要查询本月的每天电力智能通信网关的环比pr值
分析：query中的最小时间单位为天，因此unit=day，一句话中需要查询多个时间，因此"is_multi": "multi"
response：{"unit": "day", "is_multi": "multi"}
实验描述：用同样的1000条数据集，超参设置learning_rate: 0.00005，num_train_epochs: 24，Qwen1.5-14B-Chat准确率达到96%，但Qwen2.5-14B-Instruct只有76%，想请教一下为什么会退化这么多，微调时有什么需要注意的点。

#### Steps to reproduce

This happens to Qwen2.5-xB-Instruct-xxx and xxx.
The badcase can be reproduced with the following steps:
1. ...
2. ...

The following example input & output can be used:
```
system: ...
user: ...
...
```

#### Expected results

The results are expected to be ...

#### Attempts to fix

I have tried several ways to fix this, including:
1. adjusting the sampling parameters, but ...
2. prompt engineering, but ...

#### Anything else helpful for investigation

I find that this problem also happens to ...

**Comment by LaoLiulaoliu** [comment]
分别画一下loss曲线。

**Comment by xliber** [comment]
我微调其它任务也有这个问题，不过没你这么离谱，千问2.5比千问1.5的f1分数降低了3-4个点。我这边的loss曲线是正常的，可以看下你的训练参数和loss曲线吗？
