### ISSUE TITLE
[Badcase]: qwen2.5一定概率生成\\n

### ISSUE THREAD

**Issue by 520jefferson** [QwenLM/Qwen2.5#1021]
### Model Series

Qwen2.5

### What are the models used?

https://huggingface.co/Qwen/Qwen2.5-72B-Instruct

### What is the scenario where the problem happened?

megatron SFT  + hf infer 

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

megatron框架训练

### Description

1，SFT时使用qwen2 72b 的编码数据 + 使用Qwen2.5-72b-instruct作为底座
2，如果底座是Qwen2-72b-instruct时，训练完专hf model后，解码正常，没出现过\\n。 如果底座是Qwen2.5-72b-instruct时，解码有一定概率输出"\\n"而不是正常的换行。

因为md5sum vocab.json时值一样，所以我就直接换底座训练了。解码发现有这个问题，潜在的原因是啥？

**Comment by x22x22** [comment]
@520jefferson 请问解决了吗？能分享一下原因和解决方法吗？谢谢!
