### ISSUE TITLE
[Badcase]: openai.BadRequestError: Error code: 400 - {'error': {'message': 'unexpected EOF', 'type': 'invalid_request_error', 'param': None, 'code': None}}

### ISSUE THREAD

**Issue by XyLove0223** [QwenLM/Qwen2.5#1026]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-72B-Instruct

### What is the scenario where the problem happened?

Ollama

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

using local computer can run :

```
from openai import OpenAI
client = OpenAI(
    base_url='http://.........:8000/v1/',
    api_key='ollama',  # required but ignored
)
chat_completion = client.chat.completions.create(
    messages=[
        {
            'role': 'user',
            'content': 'Say this is a test',
        }
    ],
    model='qwen2.5:72b',
)
print(chat_completion)
```

but at the other computer 

```
:Error occurred: Error code: 400 - {'error': {'message': 'unexpected EOF', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

#### Steps to reproduce

This happens to Qwen2.5-xB-Instruct-xxx and xxx.
The badcase can be reproduced with the following steps:
1. ...
2. ...

The following example input & output can be used:
```
system: ...
user: ...
...
```

#### Expected results

The results are expected to be ...

#### Attempts to fix

I have tried several ways to fix this, including:
1. adjusting the sampling parameters, but ...
2. prompt engineering, but ...

#### Anything else helpful for investigation

I find that this problem also happens to ...

**Comment by XyLove0223** [comment]
PS D:\test> # 获取返回的原始内容
PS D:\test> $response = Invoke-WebRequest -Uri http://:8000/api/generate -Method POST -Body '{"model": "qwen2.5:72b", "prompt": "为什么草是绿的？"}' -ContentType 'application/json'
PS D:\test> 
PS D:\test> # 查看原始内容
PS D:\test> $rawContent = $response.RawContent
PS D:\test>
PS D:\test> # 将返回内容从 NDJSON 格式转换为 JSON 格式
PS D:\test> # 这里假设内容是一行一行的 JSON 对象
PS D:\test> $lines = $rawContent -split "`n"  # 按行分隔
PS D:\test>
PS D:\test> # 解析每一行 JSON
PS D:\test> foreach ($line in $lines) {
>>     try {
>>         $json = $line | ConvertFrom-Json
>>         # 输出解析后的内容
>>         $json
>>     } catch {
>>         Write-Host "无法解析的行：$line"
>>     }
>> }
无法解析的行：HTTP/1.1 200 OK
无法解析的行：Transfer-Encoding: chunked
无法解析的行：Content-Type: application/x-ndjson
无法解析的行：Date: Sun, 20 Oct 2024 13:26:24 GMT

model       created_at                     response   done
-----       ----------                     --------   ----
qwen2.5:72b 2024-10-20T13:26:24.488869105Z ??????    False
qwen2.5:72b 2024-10-20T13:26:24.565323044Z ???       False
qwen2.5:72b 2024-10-20T13:26:24.642167784Z ????????? False
qwen2.5:72b 2024-10-20T13:26:24.710467701Z ??????    False
qwen2.5:72b 2024-10-20T13:26:24.777325371Z ??????    False
qwen2.5:72b 2024-10-20T13:26:24.844375228Z ??????    False
qwen2.5:72b 2024-10-20T13:26:24.906853638Z ??????    False
qwen2.5:72b 2024-10-20T13:26:24.967298989Z ??????    False
qwen2.5:72b 2024-10-20T13:26:25.027440419Z ??????    False
qwen2.5:72b 2024-10-20T13:26:25.087232675Z ???       False
qwen2.5:72b 2024-10-20T13:26:25.144918405Z ????????? False
qwen2.5:72b 2024-10-20T13:26:25.200894836Z ????????? False
qwen2.5:72b 2024-10-20T13:26:25.255961725Z ??????    False
qwen2.5:72b 2024-10-20T13:26:25.309884705Z ???       False
qwen2.5:72b 2024-10-20T13:26:25.363755727Z ??????    False
qwen2.5:72b 2024-10-20T13:26:25.417717815Z ??????    False
qwen2.5:72b 2024-10-20T13:26:25.470564486Z ???       False
qwen2.5:72b 2024-10-20T13:26:25.523020636Z ??????    False
qwen2.5:72b 2024-10-20T13:26:25.575704171Z ??????    False
qwen2.5:72b 2024-10-20T13:26:25.628040761Z ????????? False
qwen2.5:72b 2024-10-20T13:26:25.680473446Z ???       False
qwen2.5:72b 2024-10-20T13:26:25.732600809Z ????      False
qwen2.5:72b 2024-10-20T13:26:25.785217302Z            True

**Comment by jklj077** [comment]
for the OpenAI API, does it work at the local computer?

**Comment by XyLove0223** [comment]
> for the OpenAI API, does it work at the local computer?

Yes, it's normal for it to be encoded locally

**Comment by jklj077** [comment]
> > for the OpenAI API, does it work at the local computer?
> 
> Yes, it's normal for it to be encoded locally

If so, both ollama and the model are working properly. 

For the OpenAI API with Python, try upgrading the openai package or ollama.

For the generate API with PowerShell, try changing the encoding/codepage to UTF-8.

**Comment by XyLove0223** [comment]
Could you provide a usable version of OpenAI? After updating, it shows that “from openai import OpenAI”can't be used, and I'm currently using UTF-8. I don't understand why both input and output encodings are incorrect.

**Comment by XyLove0223** [comment]
> > > for the OpenAI API, does it work at the local computer?
> > 
> > 
> > Yes, it's normal for it to be encoded locally
> 
> If so, both ollama and the model are working properly.
> 
> For the OpenAI API with Python, try upgrading the openai package or ollama at the other computer.
> 
> For the generate API with PowerShell, try changing the encoding/codepage to UTF-8.

Could you provide a usable version of OpenAI? After updating, it shows that “from openai import OpenAI”can't be used, and I'm currently using UTF-8. I don't understand why both input and output encodings are incorrect.
