### ISSUE TITLE
[REQUEST]: 

### ISSUE THREAD

**Issue by DAAworld** [QwenLM/Qwen2.5#1040]
### Has this been supported or requested before?

- [X] I have checked [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io).
- [X] I have checked the documentation of the related framework.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### What is this feature about?

请问是否支持openai的client.beta.chat.completions.parse方法？

### Proposal

新的openai的sdk有个parse方法，使用它调用qwen模型的时候，显示不支持这样的调用？qwen模型有计划支持吗？

### Contributions are welcomed

- [ ] I am willing to help implement this feature.

**Comment by jklj077** [comment]
looks like a pure API feature. which service provider do you use? Aliyun modelstuido/dashscope? vllm?
