### ISSUE TITLE
[Badcase]: 用mlx框架把Qwen2.5-3B-Instruct转换为mlx版本后，又用mlx_lm.convert把mlx版本的模型进行int4量化，最后进行推理的时候报错：ValueError: [dequantize] The matrix should be given as a uint32

### ISSUE THREAD

**Issue by ghoshadow** [QwenLM/Qwen2.5#1041]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-3B-Instruct

### What is the scenario where the problem happened?

Qwen2.5-3B-Instruct 被mlx量化后反量化失败

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

Model Name: MacBook Air
Model Identifier: Mac15,12
Model Number: MXCR3CH/A
Chip: Apple M3
Total Number of Cores: 8 (4 performance and 4 efficiency)
Memory: 16 GB

Package            Version
------------------ -------------
aiohappyeyeballs   2.4.3
aiohttp            3.10.10
aiosignal          1.3.1
async-timeout      4.0.3
attrs              24.2.0
Brotli             1.1.0
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.4.0
colorama           0.4.6
datasets           3.0.2
dill               0.3.8
filelock           3.16.1
frozenlist         1.5.0
fsspec             2024.10.0
gmpy2              2.1.2
h2                 4.1.0
hpack              4.0.0
huggingface-hub    0.26.2
hyperframe         6.0.1
idna               3.10
Jinja2             3.1.4
MarkupSafe         3.0.2
mlx                0.19.1
mlx-lm             0.19.2
mpmath             1.3.0
multidict          6.1.0
multiprocess       0.70.16
networkx           3.3
numpy              1.26.4
packaging          24.1
pandas             2.2.3
pip                24.2
propcache          0.2.0
protobuf           4.25.3
pyarrow            17.0.0
pycparser          2.22
PySocks            1.7.1
python-dateutil    2.9.0
pytz               2024.1
PyYAML             6.0.2
regex              2024.9.11
requests           2.32.3
safetensors        0.4.5
sentencepiece      0.2.0
setuptools         75.1.0
simpleaudio        1.0.4
six                1.16.0
sympy              1.13.2
tokenizers         0.20.1
torch              2.3.0.post101
tqdm               4.66.5
transformers       4.46.0
typing_extensions  4.12.2
tzdata             2024.2
urllib3            2.2.3
wheel              0.44.0
xxhash             3.5.0
yarl               1.16.0
zstandard          0.23.0

### Description

用mlx框架把Qwen2.5-3B-Instruct转换为mlx版本后，又用mlx_lm.convert把mlx版本的模型进行int4量化，最后进行推理的时候报错：The matrix should be given as a uint32

错误信息如下:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/bilibot/bin/mlx_lm.generate", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/generate.py", line 219, in main
    response = generate(
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/utils.py", line 336, in generate
    for n, (token, logprobs) in zip(
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/utils.py", line 247, in generate_step
    y, logprobs = _step(y)
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/utils.py", line 228, in _step
    logits = model(y[None], cache=prompt_cache)
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/models/qwen2.py", line 181, in __call__
    out = self.model(inputs, cache)
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx_lm/models/qwen2.py", line 154, in __call__
    h = self.embed_tokens(inputs)
  File "/opt/anaconda3/envs/bilibot/lib/python3.10/site-packages/mlx/nn/layers/quantized.py", line 94, in __call__
    out = mx.dequantize(
ValueError: [dequantize] The matrix should be given as a uint32

**Comment by jklj077** [comment]
does this also happen to the 1.5B or the 0.5B models?

**Comment by ghoshadow** [comment]
yes!This error occurs in every version of the model.

**Comment by ghoshadow** [comment]
> does this also happen to the 1.5B or the 0.5B models?

yes！this error occurs in every version of the model

**Comment by chaihahaha** [comment]
I also have exactly the same error for mlx-community/miqumaid-70b, this mlx model cannot be inferred after quantized to 4bit.

**Comment by angeloskath** [comment]
It seems to run fine when downloaded from HF and quantized. Could you share more information? Could you clean your huggingface cache and redownload the model using mlx? Can you upgrade mlx and mlx-lm to the latest on main or PyPI?
