### ISSUE TITLE
[Bug]: Use of the term "open source" to describe qwen when the training data is not open

### ISSUE THREAD

**Issue by phly95** [QwenLM/Qwen2.5#1055]
### Model Series

Qwen2.5

### What are the models used?

qwen 2.5

### What is the scenario where the problem happened?

all

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

All

### Log output

```shell
N/A
```

### Description

Use of the term "open source" to describe qwen when the training data is not open is incorrect usage of the term. For something to be open source, it requires that all components required to "compile" the application are available. If you consider the trained model a "binary" then the training data is the "source code". If you do not have that data, it is not "open source", but rather "open weights". Please correct all documentation to use the correct term.

**Comment by jklj077** [comment]
we mostly use the term open-weight. please open a PR for the ones you found.

**Comment by phly95** [comment]
https://qwenlm.github.io/blog/qwen2.5/ uses the term for example.

**Comment by jklj077** [comment]
different repo: https://github.com/QwenLM/qwenlm.github.io
