### ISSUE TITLE
[Badcase]: 函数调用结果和目标预期不符

### ISSUE THREAD

**Issue by akai-shuuichi** [QwenLM/Qwen2.5#1075]
### Model Series

Qwen2.5

### What are the models used?

Qwe2.5-32B-Instruct

### What is the scenario where the problem happened?

Qwen2.5-32B-Instruct-AWQ on lmdeploy

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

Package                   Version
------------------------- -----------
lmdeploy                  0.6.2.post1

### Description

[1073](https://github.com/QwenLM/Qwen2.5/discussions/1073)的后续，
我最近在尝试支持lmdeploy的函数调用，但是在解析工具时，遇到一些问题：
输入prompt：

`<|im_start|>system
你是一个智能机器人
#Tools

You may call one or more functions to assist with the user query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{"description": "获取订单的退款进度", "name": "getOrderDetail", "parameters": {"type": "object", "properties": {"orderId": {"type": "string", "description": "订单号，如9230182321"}}, "required": ["orderId"]}}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <args-json-object>}
</tool_call><|im_end|>
<|im_start|>user
告诉我的12345678订单退款进度如何<|im_end|>
<|im_start|>assistant

<|im_start|>user

<tool_response>
今天的天气很好
</tool_response><|im_end|>
<|im_start|>assistant
`

输出token：
`
<tool_call>
{"name": "getOrderDetail", "arguments": {"orderId": "12345678"}}
</tool_call>
1+1等于2。关于您的订单退款进度，我将为您查询。
`

符合仅输出<tool_call>json</tool_call>的结构，看上去不符合常理的问题会破坏这种结构

**Comment by jklj077** [comment]
the prompt does not seem correct.

https://qwen.readthedocs.io/en/latest/framework/function_call.html#qwen2-5-function-calling-templates

**Comment by akai-shuuichi** [comment]
> the prompt does not seem correct.
> 
> https://qwen.readthedocs.io/en/latest/framework/function_call.html#qwen2-5-function-calling-templates

谢谢提醒！您是对的，如果我修改成：
```
<|im_start|>system
你是一个智能机器人
#Tools

You may call one or more functions to assist with the user query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{"description": "获取订单的退款进度", "name": "getOrderDetail", "parameters": {"type": "object", "properties": {"orderId": {"type": "string", "description": "订单号，如9230182321"}}, "required": ["orderId"]}}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <args-json-object>}
</tool_call><|im_end|>
<|im_start|>user
告诉我的12345678订单退款进度如何<|im_end|>
<|im_start|>assistant
<tool_call>
{"name": "getOrderDetail, "arguments": "{\"orderId\": \"12345678\"}"
</tool_call>
}<|im_start|>user
<tool_response>
今天的天气很好
</tool_response>
<|im_end|>
<|im_start|>assistant
```
就可以得到一个纯文本的返回
```
对不起，似乎您提供的订单号与预期的格式不符，或者系统中没有找到该订单号。您能否提供一个有效的订单号，以便我可以查询该订单的退款进度？或者，请确认您提供的订单号是否正确。您提供的信息是关于天气的，而不是订单详情
```
