### ISSUE TITLE
[Bug]: 在有gpu的机器上，docker中使用ollama run qwen2.5:1.5时，报错server cpu not listed

### ISSUE THREAD

**Issue by 151812117** [QwenLM/Qwen2.5#1081]
### Model Series

Qwen2.5

### What are the models used?

qwen2.5:1.5b

### What is the scenario where the problem happened?

[Bug]: 在有gpu的机器上，启动docker（docker run试过带--gpu=all和不带的），在docker中使用ollama run qwen2.5:1.5时，报错server cpu not listed in available servers map[]

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

docker中OS: ubuntu 22.04.4
物理机GPU: NVIDIA T4
物理机NVIDIA driver: 470.82.01
物理机CUDA: 11.4 (通过nvidia-smi查看)

### Log output

```shell
level-ERROR source=server.go:282 msg="server list inconsistent" error="[0] server cpu not listed in available server map[]"
level=ERROR source=server.go:444 msg="unable to load any llama server" error="[0] server cpu not listed in available server map[]"
```

#### Steps to reproduce

This happens to Qwen2.5-xB-Instruct-xxx and xxx.
The problem can be reproduced with the following steps:
1. docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama：0.3.9
2. docker exec -it xxxxxx /bin/bash
3. ollama run qwen2.5:1.5b，报错server cpu not listed in available servers map[]

#### Expected results

The results are expected to be ...

#### Attempts to fix

I have tried several ways to fix this, including:

#### Anything else helpful for investigation

I find that this problem also happens to ...

**Comment by jklj077** [comment]
- https://github.com/ollama/ollama/issues/7502
- https://github.com/ollama/ollama/issues/4548

**Comment by 151812117** [comment]
that works
