### ISSUE TITLE
[Badcase]: 使用Reasoning数据微调2.0成功，但是2.5失败

### ISSUE THREAD

**Issue by UESTCthb** [QwenLM/Qwen2.5#1085]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-72B-Instruct

### What is the scenario where the problem happened?

Qwen2.5-72B-Instruct用reasoning数据微调，模型无法收敛

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

GPU： H100
DATASET： KingNish/reasoning-base-20k
batch size： 1
max_length:int = 3000
batch_size:int = 1
gradient_accumulation_steps:int = 16
log_iter:int = 10
max_lr:float = 2e-3
min_lr:float = 2e-4
warmup_steps:int = 1000

#### Steps to reproduce

This happens to Qwen2.5-72B-Instruct.
The badcase can be reproduced with the following steps:
max_length:int = 3000
batch_size:int = 1
gradient_accumulation_steps:int = 16
log_iter:int = 10
max_lr:float = 2e-3
min_lr:float = 2e-4
warmup_steps:int = 1000
使用如上参数微调reasoning 推理模型。数据集：KingNish/reasoning-base-20k。相同的代码和参数在Qwen2.0-72B-Instruct上成功，但是Qwen2.5-72B-Instruct无法收敛。backward报错。
并且对于Qwen2.0-72B-Instruct，如果学习率降低一个量级也会出现无法收敛的情况

**Comment by jklj077** [comment]
what's the error in the backward pass?

**Comment by UESTCthb** [comment]
Error shows at the bottom of the file. Same codes works on Qwen2.0-72B-Instruct.


田鸿博
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QwenLM/Qwen2.5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月19日(星期二) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QwenLM/Qwen2.5] [Badcase]: 使用Reasoning数据微调2.0成功，但是2.5失败 (Issue #1085)





 
what's the error in the backward pass?
