### ISSUE TITLE
[BUG]: autoawq 0.2.7量化得到模型，无法使用vllm进行推理

### ISSUE THREAD

**Issue by dcdmm** [QwenLM/Qwen2.5#1117]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-1.5B-Instruct

### What is the scenario where the problem happened?

量化模型大小只有1.1G

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

None

### Description

![image](https://github.com/user-attachments/assets/bc7e7996-39d6-4430-a1ab-46dbee447871)
![Uploading image.png…]()

**Comment by jklj077** [comment]
Although Qwen2.5-1.5B-Instruct uses tied embedding, the provided Qwen2.5-1.5B-Instruct-AWQ stores both the embedding and the lm head due to compatibility concerns. You can verfiy that by checking the safetensor content: <https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-AWQ?show_file_info=model.safetensors>. It is not necessary, and it is normal to obtain a smaller model if you've quantized the model on your own.

**Comment by dcdmm** [comment]
> Although Qwen2.5-1.5B-Instruct uses tied embedding, the provided Qwen2.5-1.5B-Instruct-AWQ stores both the embedding and the lm head due to compatibility concerns. You can verfiy that by checking the safetensor content: https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-AWQ?show_file_info=model.safetensors. It is not necessary, and it is normal to obtain a smaller model if you've quantized the model on your own.

The size of the model after quantization by qwen is 1.6G, and vllm can be used normally, but the size of my quantized model is only 1.1G. Here is my quantization code:
```python
model_path = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoAWQForCausalLM.from_pretrained(model_path, device_map="auto", safetensors=True)


def load_dolly():
    data = load_from_disk("databricks_databricks-dolly-15k_train")
    def concatenate_data(x):
        msg = [
            {"role": "system", "content": x['instruction']},
            {"role": "user", "content": x['context']},
            {"role": "assistant", "content": x['response']}
        ]
        text = tokenizer.apply_chat_template(msg, tokenize=False, add_generation_prompt=False)
        return {"text": text.strip()}

    concatenated = data.map(concatenate_data)
    return [text for text in concatenated["text"]]


quant_config = {"zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM"}
model.quantize(tokenizer, quant_config=quant_config,
               # Custom Data(Note that currently all samples above 512 in length are discarded.)
               calib_data=load_dolly())
````

**Comment by jklj077** [comment]
what's the problem then? as I have mentioned, it's normal to obtain a smaller model if you've quantized the model yourself. the provided Qwen2.5-1.5B-Instruct-AWQ is larger than it should be.

**Comment by dcdmm** [comment]
> what's the problem then? as I have mentioned, it's normal to obtain a smaller model if you've quantized the model yourself. the provided Qwen2.5-1.5B-Instruct-AWQ is larger than it should be.

my model vllm output garbled characters

model_yy = "/home/code/inference/Qwen2.5-1.5B-Instruct-CAWQ"
llm = LLM(model=model_yy, quantization='awq')
outputs = llm.generate(["hello!"], sampling_params)
for output in outputs:
prompt = output.prompt
generated_text = output.outputs[0].text
print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

![image](https://github.com/user-attachments/assets/29e9ad04-e7ec-460b-bb10-a17c88e7379c)

The official version can be output normally
