### ISSUE TITLE
[Bug]: Huggingface Inference Demo Bug

### ISSUE THREAD

**Issue by Lyy-iiis** [QwenLM/Qwen2.5#1124]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-1.5B

### What is the scenario where the problem happened?

Inference with Huggingface Inference API

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

Simply using website of huggingface.

### Log output

```shell
Input a message to start chatting with Qwen/Qwen2.5-1.5B.
你好

让您知道чик
您好чик
涐涐想把它发给他
推送鑪让它可dfloating
donnerdialog crearcedito
senderunadi
gaia enviarsemperleden
contactus
字段'deviceW
字段则store结构中的所有库文件的URL.可能为ron
字段'状态下将从jdbc: gear whale下的库ESPNstore库中下载。ray若为selectorsUB通信場合, 增加广播线程防护ทำ減少UDP发票堵拦
字段草坪以Boolean思想，则protail和flag起点為NOT IDENTIFIED wardrEmail 和FETCHED 資料未提前設置以下變數，無法連線至播攺機 (离线託收织(寻呵护离智雷合支防土携拉陶失)反因急溶喀抗钢粒突拚哀喜吊细独気他遍是学校账号偸本能控电抵，最佳偶像补实家借粮葬止医，政军一条 máquina胎赔向一命承刘振級造滞斌接慰宕裕担繁惜恨式截

hello

ሌocêeudeittes
你好إص�争吵兀エ哇光传喟映喱特宣ع拭皓望い渝妒蛾降瞾垂曯接优学绡包谴鸥历楔迟伴放淘茫爵坑诙隆闭倍膊鐲盲洱手磨椭驯
```

#### Steps to reproduce

This happens to Qwen2.5-1.5B
The problem can be reproduced with the following steps:
1. Open https://huggingface.co/Qwen/Qwen2.5-1.5B
2. Try any input to the Inference API

#### Expected results

The results are expected to be normal

**Comment by jklj077** [comment]
Please use <https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct>.
The base model (Qwen2.5-1.5B) as stated in [the model card](https://huggingface.co/Qwen/Qwen2.5-1.5B#:~:text=We%20do%20not%20recommend%20using%20base%20language%20models%20for%20conversations) is not meant to used that way, i.e., chat.
