### ISSUE TITLE
[Badcase]: 将qwen2.5-72b的初始化维度修改成29696之后，如何导入模型

### ISSUE THREAD

**Issue by ArlanCooper** [QwenLM/Qwen2.5#1125]
### Model Series

Qwen2.5

### What are the models used?

qwen2.5-72b-insturct

### What is the scenario where the problem happened?

vllm

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

OS: Ubuntu 22.04
Python: Python 3.11
GPUs: 4 x NVIDIA A20
NVIDIA driver: 535 (from nvidia-smi)
CUDA compiler: 12.2
PyTorch: 2.3.1+cu121 

### Description

因为直接量化qwen2.5-72b-instruct，然后使用vllm，无法进行并行导入，所以，按照帮助文档，https://qwen.readthedocs.io/zh-cn/latest/quantization/gptq.html#qwen2-5-72b-instruct-gptq-int4-cannot-stop-generation-properly
先将qwen2.5-72b-instruct，进行128维的padding，然后再进行量化，将初始化的维度修改成29696，
执行的命令如下：
```
# this size is Qwen2.5-72B only
pad_size = 128

sd = model.state_dict()

for i, k in enumerate(sd):
    v = sd[k]
    print(k, i)
    # interleaving the padded zeros
    if ('mlp.up_proj.weight' in k) or ('mlp.gate_proj.weight' in k):
        prev_v = F.pad(v.unsqueeze(1), (0, 0, 0, 1, 0, 0)).reshape(29568*2, -1)[:pad_size*2]
        new_v = torch.cat([prev_v, v[pad_size:]], dim=0)
        sd[k] = new_v
    elif 'mlp.down_proj.weight' in k:
        prev_v= F.pad(v.unsqueeze(2), (0, 1)).reshape(8192, 29568*2)[:, :pad_size*2]
        new_v = torch.cat([prev_v, v[:, pad_size:]], dim=1)
        sd[k] = new_v

# this is a very large file; make sure your RAM is enough to load the model
torch.save(sd, '/data/share/rwq/qwen25_awq_new/pytorch_model.bin')

```
修改成功之后，只有一个pytorch_model.bin文件，然后将原文件夹的配置文件都复制过来，应该如何导入该模型呢？
我这样导入：
```
# Load model
model = AutoAWQForCausalLM.from_pretrained(model_path,device_map="cpu",trust_remote_code=True)
```
报错:
```
FileNotFoundError: No such file or directory: "/data/share/rwq/qwen25_awq_new/model-00001-of-00031.safetensors"


```

**Comment by jklj077** [comment]
please try deleting `model.safetensors.index.json`. it's part of the old weights in the safetensors format which gets loaded before the pytorch weight format: <https://github.com/huggingface/transformers/blob/5d7739f15a6e50de416977fe2cc9cb516d67edda/src/transformers/modeling_utils.py#L3723-L3754>.

**Comment by ArlanCooper** [comment]
> please try deleting `model.safetensors.index.json`. it's part of the old weights in the safetensors format which gets loaded before the pytorch weight format: https://github.com/huggingface/transformers/blob/5d7739f15a6e50de416977fe2cc9cb516d67edda/src/transformers/modeling_utils.py#L3723-L3754.

thanks, it works fine,
