### ISSUE TITLE
[Badcase]: 调用 qwen2.5-72b-instruct 模型返回 InternalError.Algo: list index out of range 错误

### ISSUE THREAD

**Issue by coolbeevip** [QwenLM/Qwen2.5#1144]
### Model Series

Qwen2.5

### What are the models used?

qwen2.5-72b-instruct

### What is the scenario where the problem happened?

InternalError.Algo: list index out of range

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

Package                                  Version
---------------------------------------- ------------
accelerate                               1.1.1
aiohttp                                  3.8.6
aiosignal                                1.3.1
altair                                   5.1.2
an_copilot                               1.24.0rc1
annotated-types                          0.7.0
anyio                                    3.7.1
asgiref                                  3.7.2
asttokens                                2.4.1
async-timeout                            4.0.3
attrs                                    23.1.0
backoff                                  2.2.1
bcrypt                                   4.1.2
beautifulsoup4                           4.12.3
bidict                                   0.22.1
black                                    23.12.0
blinker                                  1.7.0
build                                    1.1.1
cachetools                               5.3.2
certifi                                  2023.7.22
cffi                                     1.16.0
cfgv                                     3.4.0
charset-normalizer                       3.3.2
chroma-hnswlib                           0.7.3
chromadb                                 0.4.24
click                                    8.1.7
colorama                                 0.4.6
coloredlogs                              15.0.1
coverage                                 7.2.7
cryptography                             41.0.7
Cython                                   3.0.2
dataclasses-json                         0.6.2
datasets                                 3.0.0
decorator                                5.1.1
Deprecated                               1.2.14
deprecation                              2.1.0
dill                                     0.3.8
distlib                                  0.3.7
distro                                   1.9.0
docker                                   6.1.3
docutils                                 0.20.1
duckduckgo_search                        6.2.12
et-xmlfile                               1.1.0
executing                                2.0.1
fastapi                                  0.115.2
filelock                                 3.13.1
flake8                                   5.0.4
flatbuffers                              24.3.7
flit                                     3.9.0
flit_core                                3.9.0
frozenlist                               1.4.0
fsspec                                   2024.2.0
gitdb                                    4.0.11
GitPython                                3.1.40
google-auth                              2.28.2
google-search-results                    2.4.2
googleapis-common-protos                 1.63.0
gql                                      3.4.1
grandalf                                 0.8
graphql-core                             3.2.3
graphviz                                 0.20.3
grpcio                                   1.62.1
h11                                      0.14.0
httpcore                                 1.0.6
httptools                                0.6.1
httpx                                    0.27.2
httpx-sse                                0.4.0
huggingface-hub                          0.23.4
humanfriendly                            10.0
identify                                 2.5.31
idna                                     3.4
importlib-metadata                       6.8.0
importlib_resources                      6.3.0
iniconfig                                2.0.0
ipython                                  8.26.0
isort                                    5.13.1
jaraco.classes                           3.3.0
jedi                                     0.19.1
Jinja2                                   3.1.2
jiojio                                   1.2.5
jionlp                                   1.5.2
jiter                                    0.5.0
joblib                                   1.4.2
jsonpatch                                1.33
jsonpointer                              2.4
jsonschema                               4.19.2
jsonschema-specifications                2023.7.1
kafka-python3                            3.0.0
keyring                                  24.3.0
kubernetes                               29.0.0
langchain                                0.3.13
langchain-community                      0.3.2
langchain-core                           0.3.28
langchain-experimental                   0.3.3
langchain-huggingface                    0.1.2
langchain-openai                         0.2.14
langchain-plantuml                       0.0.6
langchain-text-splitters                 0.3.4
langgraph                                0.2.60
langgraph-checkpoint                     2.0.5
langgraph-sdk                            0.1.48
langsmith                                0.1.135
loguru                                   0.7.2
markdown-it-py                           3.0.0
MarkupSafe                               2.1.3
marshmallow                              3.20.1
matplotlib-inline                        0.1.7
mccabe                                   0.7.0
mdurl                                    0.1.2
mmh3                                     4.1.0
monotonic                                1.6
more-itertools                           10.1.0
mpmath                                   1.3.0
msgpack                                  1.1.0
multidict                                6.0.4
multiprocess                             0.70.16
mypy-extensions                          1.0.0
nest-asyncio                             1.6.0
networkx                                 3.3
nh3                                      0.2.14
nodeenv                                  1.8.0
numpy                                    1.26.2
oauthlib                                 3.2.2
onnxruntime                              1.17.1
openai                                   1.58.1
openapi-pydantic                         0.5.0
openpyxl                                 3.1.5
opentelemetry-api                        1.23.0
opentelemetry-exporter-otlp-proto-common 1.23.0
opentelemetry-exporter-otlp-proto-grpc   1.23.0
opentelemetry-instrumentation            0.44b0
opentelemetry-instrumentation-asgi       0.44b0
opentelemetry-instrumentation-fastapi    0.44b0
opentelemetry-proto                      1.23.0
opentelemetry-sdk                        1.23.0
opentelemetry-semantic-conventions       0.44b0
opentelemetry-util-http                  0.44b0
orjson                                   3.10.6
overrides                                7.7.0
packaging                                24.1
pandas                                   2.2.2
parso                                    0.8.4
pathspec                                 0.11.2
pexpect                                  4.9.0
Pillow                                   9.5.0
pip                                      24.2
pipdeptree                               2.23.4
pkginfo                                  1.9.6
platformdirs                             3.11.0
pluggy                                   1.3.0
posthog                                  3.5.0
pre-commit                               3.6.0
primp                                    0.6.3
prompt_toolkit                           3.0.47
protobuf                                 4.25.0
psutil                                   6.1.0
psycopg2-binary                          2.9.9
ptyprocess                               0.7.0
pulsar-client                            3.4.0
pure-eval                                0.2.2
pyarrow                                  18.1.0
pyasn1                                   0.5.1
pyasn1-modules                           0.3.0
pycodestyle                              2.9.1
pycparser                                2.21
pycryptodome                             3.19.0
pycryptodomex                            3.19.0
pydantic                                 2.10.4
pydantic_core                            2.27.2
pydantic-settings                        2.5.2
pydeck                                   0.8.1b0
pyflakes                                 2.5.0
Pygments                                 2.16.1
pygraphviz                               1.13
PyJWT                                    2.9.0
PyMySQL                                  1.1.0
pyparsing                                3.1.2
pyperclip                                1.9.0
PyPika                                   0.48.9
pyproject-flake8                         5.0.4
pyproject_hooks                          1.0.0
pytest                                   7.4.3
pytest-asyncio                           0.23.6
pytest-cov                               4.1.0
python-dateutil                          2.8.2
python-dotenv                            1.0.1
python-engineio                          4.8.0
python-multipart                         0.0.6
python-socketio                          5.9.0
pytz                                     2023.3.post1
PyYAML                                   6.0.1
pyzipper                                 0.3.6
readme-renderer                          42.0
referencing                              0.30.2
regex                                    2023.10.3
rel                                      0.4.9.9
requests                                 2.32.2
requests-oauthlib                        1.4.0
requests-toolbelt                        1.0.0
rfc3986                                  2.0.0
rich                                     13.6.0
rpds-py                                  0.12.0
rsa                                      4.9
safetensors                              0.4.3
schedule                                 1.2.1
scikit-learn                             1.5.2
scipy                                    1.14.0
sentence-transformers                    3.0.1
setuptools                               68.0.0
simple-websocket                         1.0.0
six                                      1.16.0
smmap                                    5.0.1
sniffio                                  1.3.0
soupsieve                                2.5
SQLAlchemy                               2.0.23
sse-starlette                            2.1.3
stack-data                               0.6.3
starlette                                0.40.0
streamlit                                1.37.1
sympy                                    1.13.1
tabulate                                 0.9.0
tenacity                                 8.2.3
testcontainers                           3.7.1
threadpoolctl                            3.5.0
tiktoken                                 0.7.0
tokenizers                               0.20.3
toml                                     0.10.2
tomli_w                                  1.0.0
toolz                                    0.12.0
torch                                    2.5.1
tornado                                  6.3.3
tqdm                                     4.67.1
traitlets                                5.14.3
transformers                             4.46.3
twine                                    4.0.2
typer                                    0.9.0
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2023.3
tzlocal                                  5.2
urllib3                                  2.1.0
uvicorn                                  0.29.0
uvloop                                   0.19.0
validators                               0.22.0
virtualenv                               20.24.6
watchfiles                               0.21.0
wcwidth                                  0.2.13
websocket-client                         1.7.0
websockets                               12.0
wheel                                    0.41.3
wikipedia                                1.4.0
wrapt                                    1.16.0
wsproto                                  1.2.0
xxhash                                   3.5.0
yarl                                     1.9.2
zipfile36                                0.1.3
zipp                                     3.17.0

### Description

调用 https://dashscope.aliyuncs.com/compatible-mode/v1 提供的接口服务，在使用 tools 的时候 qwen2.5-72b-instruct 会返回如下错误，使用 qwen1.5-72b-chat 模型则没有这个问题。

```shell
openai.InternalServerError: Error code: 500 - {'error': {'code': 'internal_server_error', 'param': None, 'message': '<500> InternalError.Algo: list index out of range', 'type': 'internal_server_error'}, 'id': 'chatcmpl-29672c65-6077-9e06-a097-f45cbbfca53b', 'request_id': '29672c65-6077-9e06-a097-f45cbbfca53b'}
```

**Comment by jklj077** [comment]
Hi, this repository is primarily for community support. If you are using commercial services, such as those provided by Alibaba Cloud or Aliyun, please submit a ticket to the respective service provider to receive assistance from their professional customer support team.

**Comment by coolbeevip** [comment]
> Hi, this repository is primarily for community support. If you are using commercial services, such as those provided by Alibaba Cloud or Aliyun, please submit a ticket to the respective service provider to receive assistance from their professional customer support team.

Thank you for your response.
