### ISSUE TITLE
vllm本地部署Qwen1.5-72B-chat，在一次性生成长文本的任务中，出现超出字数限制的提示

### ISSUE THREAD

**Issue by JSLW** [QwenLM/Qwen2.5#387]
vllm本地部署Qwen1.5-72B-chat，有长文本输出任务，比如一次性生成一篇超过2000字的文章，这时会提示由于字数限制，无法一次性生成
![image](https://github.com/QwenLM/Qwen1.5/assets/48468292/e21d0735-0f28-458b-b381-ab5cc83ae706)
但实际上，模型上下文的长度为32k
![image](https://github.com/QwenLM/Qwen1.5/assets/48468292/fb514651-ae03-4bb9-a617-d239c56ca48c)
已经尝试过设置max_token、max_position_embeddings和model_max_length等参数，但似乎与当前问题关系不大
那么，我应该调整哪些参数，才能避免这种情况的出现

**Comment by jklj077** [comment]
Hi! 
The model generates a built-in reminder that generating extensive articles in a single go may lead to suboptimal results. This feature isn't influenced by the generation settings, like max_new_tokens. To guide the model towards producing more content, consider refining your prompts with specific instructions. Keep in mind, though, that achieving a precise article length may not always be feasible.

**Comment by WangJianQ-cmd** [comment]
openai参数中的 max_new_tokens+输入的token 不能超过 32768

**Comment by YaoAIPro** [comment]
@JSLW 需要在模型配置文件修改最大上下文长度
![image](https://github.com/user-attachments/assets/b479bb19-b8e2-4d87-beb9-f46a11b34e02)

**Comment by jklj077** [comment]
For the record, the limit of the sequence length is not directly related to how many tokens the model can generate. The OP's issue is that the model behaviour is tuned to refuse to generate that many tokens, not that the underlying model cannot handle sequence that long. 3000 Chinese words are far fewer than 32K tokens.

For generating long content, please consider upgrading to Qwen2.5.
