### ISSUE TITLE
Any plan for Qwen2 14B and  Qwen2-32B?

### ISSUE THREAD

**Issue by loveychen** [QwenLM/Qwen2.5#482]

**Comment by hehuang139** [comment]
+1

**Comment by wciq1208** [comment]
+1

**Comment by huangguifeng** [comment]
小的小，大的大，没个合适的。还是14B或者32B 好点。希望能出这两个尺寸的。

**Comment by despairTK** [comment]
32B的Q4量化版本最适合4090单卡用户在 ollama 运行。还是希望能出个32B模型。

**Comment by lonePatient** [comment]
14B-32B是真的适合，不知道官方是否会开源对应版本。

**Comment by AkikazeQ** [comment]
不太理解为什么不出最实用的，适合目前主流中高端16G卡和24G卡用的14B和32B呢，
小的性能不如意，72B单24G卡用不了，等于不存在。

**Comment by huashiyiqike** [comment]
I will stick to Qwen1.5-14B-Chat-GPTQ-Int4, if Qwen2 14B is not available

**Comment by Liuchunyangboy** [comment]
期待

**Comment by xl298** [comment]
14B&32B please!

**Comment by youyouye** [comment]
非常需要32b，57B的根本跑不了，7b的又太弱

**Comment by alfgo** [comment]
希望14b&32b，7b真的不行

**Comment by alfgo** [comment]
7b太弱了，比glm4 9b差不少。也不如qwen1.5 14b

**Comment by SoaringTiger** [comment]
**_14b / 32b 要让广大 16G/24G 普通用户能跑起来🚀_**

**Comment by xbl916** [comment]
确实，很需要一个30b左右的模型

**Comment by huchaodi** [comment]
24G 卡同求 14b

**Comment by momomobinx** [comment]
14B&32B please!

**Comment by willzli** [comment]
不出qwen2 14B 和 32B，会导致qwen2直接没人用。qwen2重点是公布刷榜成绩，其他的不是他考虑重点。

**Comment by shesung** [comment]
铜球14B

**Comment by copper202310** [comment]
7B确实不够，需要 14B，是不是 Qwen2-14B 太强了，不开源

**Comment by xbl916** [comment]
时刻关注，希望能有

**Comment by tobchef** [comment]
8G显存gguf量化能跑的极限就是14B

**Comment by buptlihang** [comment]
同求14B

**Comment by JustinLin610** [comment]
这里做下解释。在Qwen2本次设计中，MoE是medium size的模型主力，仅仅激活14B，但是达到30B模型的效果。但当前生态对MoE的支持还不完善，57B的模型大小对于显存要求较高，我们正在计划补上14和32这两个size的模型，但这两个模型毕竟是比较大的模型，还需要一些时间。

**Comment by kele527** [comment]
> 这里做下解释。在Qwen2本次设计中，MoE是medium size的模型主力，仅仅激活14B，但是达到30B模型的效果。但当前生态对MoE的支持还不完善，57B的模型大小对于显存要求较高，我们正在计划补上14和32这两个size的模型，但这两个模型毕竟是比较大的模型，还需要一些时间。
> 
> We previously hope that the MoE model can be your choice for a medium-size model. It actually only activates only 14B params in each forward pass but it can achieve the expected performance of a around 30B dense model. We are at the same time pushing the support for this model in the community and we understand that this 57B model requires large RAM. We are planning about providing 14B and 32B models, but this should take some time. Stay tuned.

预计大概什么时候发布啊？

**Comment by iiiusky** [comment]
72b最少单卡显存需要多大？

**Comment by kele527** [comment]
有进展吗？ 还有希望吗

**Comment by weiminw** [comment]
还有希望吗？感觉我要换模型了，等不住了

**Comment by shikimoon** [comment]
> 还有希望吗？感觉我要换模型了，等不住了

已经换了

**Comment by weiminw** [comment]
> > 还有希望吗？感觉我要换模型了，等不住了
> 
> 已经换了

你换了哪个模型？

**Comment by shikimoon** [comment]
> > > 还有希望吗？感觉我要换模型了，等不住了
> > 
> > 
> > 已经换了
> 
> 你换了哪个模型？

internvl2-26b

**Comment by lonePatient** [comment]
> > > > 还有希望吗？感觉我要换模型了，等不住了
> > > 
> > > 
> > > 已经换了
> > 
> > 
> > 你换了哪个模型？
> 
> internvl2-26b

效果如何

**Comment by tuobay** [comment]
> > > > 还有希望吗？感觉我要换模型了，等不住了
> > > 
> > > 
> > > 已经换了
> > 
> > 
> > 你换了哪个模型？
> 
> internvl2-26b

hi，效果如何，用的是文字那部分吗

**Comment by lonePatient** [comment]
负责人都走了。

**Comment by weiminw** [comment]
> > > > > > 还有希望吗？感觉我要换模型了，等不住了
> > > > > 
> > > > > 
> > > > > 已经换了
> > > > 
> > > > 
> > > > 你换了哪个模型？
> > > 
> > > 
> > > internvl2-26b
> > 
> > 效果如何
> 
> 多模态能力还行。文本能力不如qwen15-14b

llama3.1出来了，看看有没有中文调优的。qwen 开源 感觉太凉

**Comment by kele527** [comment]
千问是不是不维护了？

**Comment by meigami0** [comment]
没有Qwen2-32b可以用gemma2-27b

**Comment by kele527** [comment]
> 没有Qwen2-32b可以用gemma2-27b

gemma2-27b感觉还是不如qwen2  可惜qwen2不给力

**Comment by weiminw** [comment]
> 没有Qwen2-32b可以用gemma2-27b

gemma2 27b vllm 支持吗？另外中文支持如何？会不会问中文，中英夹杂回复？

**Comment by huliang2016** [comment]
> 这里做下解释。在Qwen2本次设计中，MoE是medium size的模型主力，仅仅激活14B，但是达到30B模型的效果。但当前生态对MoE的支持还不完善，57B的模型大小对于显存要求较高，我们正在计划补上14和32这两个size的模型，但这两个模型毕竟是比较大的模型，还需要一些时间。
> 
> We previously hope that the MoE model can be your choice for a medium-size model. It actually only activates only 14B params in each forward pass but it can achieve the expected performance of a around 30B dense model. We are at the same time pushing the support for this model in the community and we understand that this 57B model requires large RAM. We are planning about providing 14B and 32B models, but this should take some time. Stay tuned.

@JustinLin610 Hello, is there any update on this?

**Comment by rufeng-h** [comment]
已经过去3个多月了，14B和32B的有计划开源吗

**Comment by VirgilG72** [comment]
> 这里做下解释。在Qwen2本次设计中，MoE是medium size的模型主力，仅仅激活14B，但是达到30B模型的效果。但当前生态对MoE的支持还不完善，57B的模型大小对于显存要求较高，我们正在计划补上14和32这两个size的模型，但这两个模型毕竟是比较大的模型，还需要一些时间。
> 
> We previously hope that the MoE model can be your choice for a medium-size model. It actually only activates only 14B params in each forward pass but it can achieve the expected performance of a around 30B dense model. We are at the same time pushing the support for this model in the community and we understand that this 57B model requires large RAM. We are planning about providing 14B and 32B models, but this should take some time. Stay tuned.
@JustinLin610 请问进展如何了？

**Comment by VirgilG72** [comment]
> > 这里做下解释。在Qwen2本次设计中，MoE是medium size的模型主力，仅仅激活14B，但是达到30B模型的效果。但当前生态对MoE的支持还不完善，57B的模型大小对于显存要求较高，我们正在计划补上14和32这两个size的模型，但这两个模型毕竟是比较大的模型，还需要一些时间。
> > We previously hope that the MoE model can be your choice for a medium-size model. It actually only activates only 14B params in each forward pass but it can achieve the expected performance of a around 30B dense model. We are at the same time pushing the support for this model in the community and we understand that this 57B model requires large RAM. We are planning about providing 14B and 32B models, but this should take some time. Stay tuned.
> > @JustinLin610 请问进展如何了？

@jklj077 你好 请问14B和32B还有计划发布吗？

**Comment by zhufeizzz** [comment]
@JustinLin610 请问有14B和32B的发布计划吗？

**Comment by JamenceTom** [comment]
> @JustinLin610 请问有14B和32B的发布计划吗？

Qwen2.5来了

**Comment by momomobinx** [comment]
可以关闭了

**Comment by jklj077** [comment]
Hi, all! We have released the Qwen2.5 series. This time there are 3 extra model sizes: 3B, 14B, and 32B for more possibilities. Check our [blog](https://qwenlm.github.io/blog/qwen2.5) for more!
