### ISSUE TITLE
使用vllm部署qwen2-72b-instruct重复生成的问题

### ISSUE THREAD

**Issue by Kk1984up** [QwenLM/Qwen2.5#576]

**Comment by jklj077** [comment]
Hi, any cases that you could share?

**Comment by gengjiawen** [comment]
@jklj077 我是使用阿里云的api，可以稳定复现 qwen2-72b-instruct

[qwen2-72b_128k_bug.txt](https://github.com/user-attachments/files/15858200/qwen2-72b_128k_bug.txt)

**Comment by kenvix** [comment]
应该和 #513 是相同问题

**Comment by jklj077** [comment]
@gengjiawen may I know what's the prompt and the inferece parameter used?

**Comment by jklj077** [comment]
@kenvix provide more info could help: which model? is the model quantized? what's the input? what's the generation config? will the default sampling parameters help?

**Comment by llmforever** [comment]
> @kenvix provide more info could help: which model? is the model quantized? what's the input? what's the generation config? will the default sampling parameters help?

出现同样的问题，使用qwen2-72b-instruct模型，bf16/awq/gptq int4 int8 均有该问题，输入为长文本（多轮对话，尤其重复问题问多遍）或者极短文本（如vllm测试脚本，只有开始两个字）均非常容易激发这个问题，使用transformer/vllm/lmdeploy推理都会出现。使用默认生成参数，微调频率惩罚、重复惩罚也没有任何改善。如需要，可提供多个case

**Comment by jingyibo123** [comment]
> > @kenvix provide more info could help: which model? is the model quantized? what's the input? what's the generation config? will the default sampling parameters help?
> 
> 出现同样的问题，使用qwen2-72b-instruct模型，bf16/awq/gptq int4 int8 均有该问题，输入为长文本（多轮对话，尤其重复问题问多遍）或者极短文本（如vllm测试脚本，只有开始两个字）均非常容易激发这个问题，使用transformer/vllm/lmdeploy推理都会出现。使用默认生成参数，微调频率惩罚、重复惩罚也没有任何改善。如需要，可提供多个case。另外，之前测试阿里云云服务，平台上的qwen2-72b-instruct也有同样的问题

@llmforever 上下文长度是默认的32K吗，还是扩展到128K了？
