### ISSUE TITLE
Qwen2 提示失败：翻译后续写

### ISSUE THREAD

**Issue by wencan** [QwenLM/Qwen2.5#591]
不知道这个算不算BUG
https://huggingface.co/spaces/Qwen/Qwen2-72B-Instruct

提示文本如下（或者用英文提示，效果一样）：
```
你是一名翻译官。这段文本来自the ZeroMQ guide，知识领域为计算机科学，原语言是英文，请翻译为中文，不要使用机器翻译风格，不要添加译注。
```

翻译原文本来自 https://zguide.zeromq.org/ ，找以符号 : 结尾的段落，比如：
```
There are, in my experience, roughly three ways to connect clients to servers. Each needs a specific approach to reliability:
```
多找几段试试。
一定概率下，模型会在后面添加代码块或者文本。有时犯错的概率几乎百分之百。
gemini也会犯一样的错误，但概率低得多，百分之五以下。

**Comment by jklj077** [comment]
it should happen less for Qwen2.5.

![image](https://github.com/user-attachments/assets/e0ca475a-f835-4b7a-9773-f9c8863eba1a)
![image](https://github.com/user-attachments/assets/45e2559a-1558-457e-be76-7c00fa590503)
