### ISSUE TITLE
再次预训练

### ISSUE THREAD

**Issue by wangxun6** [QwenLM/Qwen2.5#667]
我想请问一下基于qwen2，用自己的数据集，再次进行预训练，应该怎么去做呢，有相关脚本吗？

**Comment by xsank** [comment]
mark

**Comment by minxiansheng** [comment]
@wangxun6 你知道怎么弄了吗，我也需要这个，不会没思路

**Comment by wangxun6** [comment]
我目前在qwen2 7B上进行了小规模的无监督文本的预训练。后续指令微调应该用多大的数据量呢。需要多少QA对呢。

**Comment by yangjianxin1** [comment]
如果需要进行预训练的话，可以尝试使用[Llama Factory](https://github.com/hiyouga/LLaMA-Factory)

**Comment by yangjianxin1** [comment]
> 我目前在qwen2 7B上进行了小规模的无监督文本的预训练。后续指令微调应该用多大的数据量呢。需要多少QA对呢。

具体还是看你手边的数据量，上万条数据做sft可以获得蛮不错的效果，当然高质量数据多多益善。

**Comment by hailey123123** [comment]
> 我目前在qwen2 7B上进行了小规模的无监督文本的预训练。后续指令微调应该用多大的数据量呢。需要多少QA对呢。

请问哪里能找到预训练代码呢，我找到的都是微调代码

**Comment by iissy** [comment]
同问，我也想要一份从0开始预训练的官方代码，自己写的跑得效果不理想。

**Comment by wangxun6** [comment]
还有就是我之前拿7B做的预训练，但是generate生成的内容效果特别差，请问这个是我数据集量较小的原因吗？
