### ISSUE TITLE
Qwen2-72B-Instruct-gptq-int4重复问题

### ISSUE THREAD

**Issue by Storm0921** [QwenLM/Qwen2.5#675]
机器A800，vLLM 0.5.0，prompt是开始，输出max tokens=2048，temperature设0.7

vLLM加载Qwen2-72B-Instruct-gptq-int4，使用vLLM的benchmark脚本来做并发测试，无论是1个并发限制还是10个并发限制，输出均会重复。
https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py

![企业微信截图_1718760902864](https://github.com/QwenLM/Qwen2/assets/57557769/380b10a9-77bf-429c-9e04-1e528fd5e43c)

![企业微信截图_1718760893772](https://github.com/QwenLM/Qwen2/assets/57557769/b1b261da-464f-4d86-b5ae-08eb54ce806f)

当然我也测试了无限制并发的情况下，也会生成重复

![image](https://github.com/QwenLM/Qwen2/assets/57557769/5da613c0-f9e1-4b2f-bf4e-85d28c720bc8)

**Comment by jklj077** [comment]
Hi, how did you start that script? Did you change the script to set the temperature?

**Comment by Storm0921** [comment]
> Hi, how did you start that script? Did you change the script to set the temperature?

https://github.com/vllm-project/vllm/blob/main/benchmarks/backend_request_func.py#L321
修改这一行的温度值。直接python run这个benchmark_serving.py，修改一下args里面的地址，模型啥的

**Comment by jklj077** [comment]
Hi, if you have modified the script and would like to receive coherent responses, you probably also want to modify the reptition penalty, stop tokens, endpoint (use chat completions) and such.

**Comment by Storm0921** [comment]
> Hi, if you have modified the script and would like to receive coherent responses, you probably also want to modify the reptition penalty, stop tokens, endpoint (use chat completions) and such.

你能花点时间去试一下吗？，我设置的reptition penalty=1.0，stop= ["<|im_end|>", "<|endoftext|>"], endpoint is openai-chat。
在Qwen2-72B-gptq-int4上就是那么重复，但是相同设置下Qwen1.5-72B-gptq-int4不会重复

**Comment by jklj077** [comment]
Hi, I had tested the whole thing before my first comment.

**Comment by Storm0921** [comment]
> Hi, I had tested the whole thing before my first comment.

but, Have you not experienced any duplication? I see many buddies, just like me, experiencing repetition. What's going on...

**Comment by jklj077** [comment]
Hi, please **share the cases** so that we can try to reproduce.

**Comment by Storm0921** [comment]
[vllm_benchmark.zip](https://github.com/user-attachments/files/15912331/vllm_benchmark.zip)

@jklj077

**Comment by jklj077** [comment]
Hi, the files you provided were heavily modified and a lot of things were hard-coded. After the backend kept giving me Bad Request, I just gave up.

But your request appears to be just "开始", and that's case I need. I can reproduce the issue with vllm==0.5.0.post1 and default generation parameters (temperature=0.7, top_p=0.8, top_k=20, repetition_penalty=1.05). About 10% of the responses are highly repetitive. But it did not happen to "结束" though.

Do you happen to have any other real world cases that can be shared?

**Comment by Storm0921** [comment]
> Hi, the files you provided were heavily modified and a lot of things were hard-coded. After the backend kept giving me Bad Request, I just gave up.
> 
> But your request appears to be just "开始", and that's case I need. I can reproduce the issue with vllm==0.5.0.post1 and default generation parameters (temperature=0.7, top_p=0.8, top_k=20, repetition_penalty=1.05). About 10% of the responses are highly repetitive. But it did not happen to "结束" though.
> 
> Do you happen to have any other real world cases that can be shared?

When using some conversation data for benchmark testing before, I encountered some occasional duplicate problems that were not recorded. I suggest that you use some open-source Chinese datasets for some more conversations, which should be able to reproduce them, thanks.

**Comment by hqh312** [comment]
我也遇到了这个问题，模型推理会重复回答问题，直至超过max_model_len

**Comment by jklj077** [comment]
@hqh312 Hi, which model, which framework, and are there any cases you could share?

**Comment by stay-leave** [comment]
我也在dify使用中出现了该问题。
我用VLLM部署为OpenAI接口，在dify作为一个节点作为LLM，偶发该问题。奇怪的是我直接问LLM相同的东西没有问题。

**Comment by hqh312** [comment]
> @hqh312你好，什么模型，什么框架，有什么案例可以分享吗？
模型：Qwen2-72B-Instruct-AWQ
框架：vllm
样例：
     输入：敏感话题提示
     输出：不会直接拒绝回答，很繁琐的解释了半天，然后一直循环重复

整体qwen2要比qwen1.5回答的篇幅要长很多

**Comment by Jankin66** [comment]
> 机器A800，vLLM 0.5.0，prompt是开始，输出max tokens=2048，temperature设0.7
> 
> vLLM加载Qwen2-72B-Instruct-gptq-int4，使用vLLM的benchmark脚本来做并发测试，无论是1个并发限制还是10个并发限制，输出均会重复。 https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py
> 
> ![企业微信截图_1718760902864](https://private-user-images.githubusercontent.com/57557769/340890300-380b10a9-77bf-429c-9e04-1e528fd5e43c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDM0MzksIm5iZiI6MTcyMDcwMzEzOSwicGF0aCI6Ii81NzU1Nzc2OS8zNDA4OTAzMDAtMzgwYjEwYTktNzdiZi00MjljLTllMDQtMWU1MjhmZDVlNDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODBkNGU2ZmE3NzM3ZjZiYzEwN2Q3ODdkYjUwMGI5MTIzMTlhMWE3MzkzZmY0M2NiOWE4Mjk0ZWQyNTJiOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.poU6biU-x0Kqj7ZoAdv-LfIV00OgA-RPX7ddLIPk7pk)
> 
> ![企业微信截图_1718760893772](https://private-user-images.githubusercontent.com/57557769/340890330-b1b261da-464f-4d86-b5ae-08eb54ce806f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDM0MzksIm5iZiI6MTcyMDcwMzEzOSwicGF0aCI6Ii81NzU1Nzc2OS8zNDA4OTAzMzAtYjFiMjYxZGEtNDY0Zi00ZDg2LWI1YWUtMDhlYjU0Y2U4MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOWRhNzNmMjViNDE3YmY1OGMyMzlkNTExMWFkNzQwNTgyYTYyNDI4MWVlMGYxYjI3Y2ViMzYwM2Y2NTNiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lBtAWFVyOc9PlTVxYcc7z0mjZiP8Y3MRS8ldfNPWIk)
> 
> 当然我也测试了无限制并发的情况下，也会生成重复
> 
> ![image](https://private-user-images.githubusercontent.com/57557769/340891602-5da613c0-f9e1-4b2f-bf4e-85d28c720bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDM0MzksIm5iZiI6MTcyMDcwMzEzOSwicGF0aCI6Ii81NzU1Nzc2OS8zNDA4OTE2MDItNWRhNjEzYzAtZjllMS00YjJmLWJmNGUtODVkMjhjNzIwYmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEzMDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZDNlMDNlMWEwNzIyZTdlYThiMTA2YzAxNDU0NWRhNDc5NzQ1Y2RjYWVkZGI0YTE3ZTBiYWFhMWRjM2M0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._nlegUqpqbqCblEZU4MI9Xsd4n8wffMye7LuY44jNFg)

同样遇到了，有解决吗

**Comment by wertyac** [comment]
同样问题AWQ的模型重复概率大很多，设置reptition penalty=1.1也没有解决。

**Comment by chuangzhidan** [comment]
> 同样问题AWQ的模型重复概率大很多，设置reptition penalty=1.1也没有解决。

一个A800可以跑10个并发吗？速度怎么样？

**Comment by teaguexiao** [comment]
> 我也在dify使用中出现了该问题。 我用VLLM部署为OpenAI接口，在dify作为一个节点作为LLM，偶发该问题。奇怪的是我直接问LLM相同的东西没有问题。

这个有解决吗？我遇到同样问题。

**Comment by teaguexiao** [comment]
我这里好像解决了，是在Dify的LLM设置里面把stop token手动协商<|endoftext|>和<|im_end|>能解决。Dify在去调用vllm的时候会带上这个参数

**Comment by chuangzhidan** [comment]
> 一个A800可以跑10个并发吗？速度怎么样？

**Comment by chuangzhidan** [comment]
> 机器A800，vLLM 0.5.0，prompt是开始，输出max tokens=2048，temperature设0.7
> 
> vLLM加载Qwen2-72B-Instruct-gptq-int4，使用vLLM的benchmark脚本来做并发测试，无论是1个并发限制还是10个并发限制，输出均会重复。 https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py
> 
> ![企业微信截图_1718760902864](https://private-user-images.githubusercontent.com/57557769/340890300-380b10a9-77bf-429c-9e04-1e528fd5e43c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDg0MjMsIm5iZiI6MTcyMjc0ODEyMywicGF0aCI6Ii81NzU1Nzc2OS8zNDA4OTAzMDAtMzgwYjEwYTktNzdiZi00MjljLTllMDQtMWU1MjhmZDVlNDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA1MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNDI1YTMxNTFhNGI3MWVhOTUyNjc1M2QxOWI3ZThkNmI0MGE5ODgyNjZiODRjNjBmMTY3OGQ3ZWYwZTg1NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L1zvOm95rgf2Y_4vQvoz_QLijQMeYv0UltfRNQwXqXE)
> 
> ![企业微信截图_1718760893772](https://private-user-images.githubusercontent.com/57557769/340890330-b1b261da-464f-4d86-b5ae-08eb54ce806f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDg0MjMsIm5iZiI6MTcyMjc0ODEyMywicGF0aCI6Ii81NzU1Nzc2OS8zNDA4OTAzMzAtYjFiMjYxZGEtNDY0Zi00ZDg2LWI1YWUtMDhlYjU0Y2U4MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA1MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMWE4ZGViNzU0MzY2MjdhNmU0YmZmZjhlN2NmOTM2YTEyODRiMTFmYTNkYzhkNzRjNzgxM2U4YTg3NTE4MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RR1AruZS273uj-_N8ypqQSMxogU7GHqFArR1WdzqRIA)
> 
> 当然我也测试了无限制并发的情况下，也会生成重复
> 
> ![image](https://private-user-images.githubusercontent.com/57557769/340891602-5da613c0-f9e1-4b2f-bf4e-85d28c720bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDg0MjMsIm5iZiI6MTcyMjc0ODEyMywicGF0aCI6Ii81NzU1Nzc2OS8zNDA4OTE2MDItNWRhNjEzYzAtZjllMS00YjJmLWJmNGUtODVkMjhjNzIwYmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA1MDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMGUxYzEzMThkM2NjNGQxOGMxZjQzMWM1ZDcwMWVkZWJlNWY3ZWZlM2M4OTc0YmQ1NTJiYWU5MGNjZjI3YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V1DpG7dA_gqSQqGAInKRvfmkzMif5qqxUJnfyI5MbgU)

一个A800可以跑10个并发吗？速度怎么样？

**Comment by chuangzhidan** [comment]
> 我这里好像解决了，是在Dify的LLM设置里面把stop token手动协商<|endoftext|>和<|im_end|>能解决。Dify在去调用vllm的时候会带上这个参数



> 我这里好像解决了，是在Dify的LLM设置里面把stop token手动协商<|endoftext|>和<|im_end|>能解决。Dify在去调用vllm的时候会带上这个参数

语言模型官方运行脚本，可以这么设置stop token=<|endoftext|>和<|im_end|>吗

**Comment by aikangjun** [comment]
使用非量化的模型 能解决这个问题

**Comment by jklj077** [comment]
Repetition should be less for Qwen2.5 in general. However, please do pay attention to [the known issues](https://qwen.readthedocs.io/en/latest/quantization/gptq.html). It may be required to quantize the model on your own. Please open a badcase report for specific cases.

**Comment by Jankin66** [comment]
已收到您的信件！
