### ISSUE TITLE
运行支持的128K上下文后报错

### ISSUE THREAD

**Issue by lonngxiang** [QwenLM/Qwen2.5#717]
https://huggingface.co/Qwen/Qwen2-72B-Instruct#processing-long-texts
按要求配置了，输入6万字左右报错了：BadRequestError: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 32768 tokens. However, you requested 37055 tokens in the messages, Please reduce the length of the messages.", 'type': 'BadRequestError', 'param': None, 'code': 400}

**Comment by lonngxiang** [comment]
升级vllm 0.5.0.post1版本，运行依旧报上面错误
![image](https://github.com/QwenLM/Qwen2/assets/40717349/91bca8e1-20d5-4e3a-ace6-08896578e48e)

**Comment by lonngxiang** [comment]
运行的7b模型

**Comment by lonngxiang** [comment]
@hzhwcmhf https://huggingface.co/Qwen/Qwen2-72B-Instruct/discussions/17

**Comment by hzhwcmhf** [comment]
@lonngxiang 你运行的命令中需要相应增大--max-model-len 32768 的值

**Comment by youcanyouupsb** [comment]
不设置--max-model-len 32768的话，只要模型推理服务加载运行ok，显存是够的，默认得应该是128k，我本地运行--max-model-len 设置为：16384,太大就启动加载不了，显存不够。

**Comment by lonngxiang** [comment]
> @lonngxiang 你运行的命令中需要相应增大--max-model-len 32768 的值
vllm我增加--max-model-len 80000，运行6万多字输出就这样全身！
![image](https://github.com/QwenLM/Qwen2/assets/40717349/c3a4607c-ee82-4429-9c13-7a64eb4b5ef9)

**Comment by hzhwcmhf** [comment]
@lonngxiang 试试用``--dtype bfloat16``？  float16可能会爆精度。
比较好奇你用的是什么显卡？按我们的测试80000长度需要4卡A100-80G

**Comment by lonngxiang** [comment]
> @lonngxiang 试试用`--dtype bfloat16`？ float16可能会爆精度。 比较好奇你用的是什么显卡？按我们的测试80000长度需要4卡A100-80G

2张4090

**Comment by lonngxiang** [comment]
> @lonngxiang 试试用`--dtype bfloat16`？ float16可能会爆精度。
> 
> ~比较好奇你用的是什么显卡？按我们的测试80000长度需要4卡A100-80G~ 没事了，7b单卡80G应该能开到128k

改成bfloat16，还是输出感叹号，显存看着也有空余
![image](https://github.com/QwenLM/Qwen2/assets/40717349/a4c5fecc-8e12-4e6e-843b-52c889438fd7)
![image](https://github.com/QwenLM/Qwen2/assets/40717349/edbaba78-6612-441e-93e6-367c2782a9ae)

**Comment by hzhwcmhf** [comment]
@lonngxiang 你使用的是Qwen2-7B-Instruct吗，还是量化版本？

**Comment by lonngxiang** [comment]
> @lonngxiang 你使用的是Qwen2-7B-Instruct吗，还是量化版本？

是的，无量化版本

**Comment by hzhwcmhf** [comment]
@lonngxiang 这个情况我们确实没遇见过。你可以再测试一下以下几种情况吗：
1. 这个感叹号是否和输入文本本身有关。换一个prompt会发生吗，用更短的prompt呢？
2. 这个感叹号是否和--model-max-len有关？按你原来的32768就是正常的？
3. 这个感叹号是否和config里scaling_factor有关？

**Comment by lonngxiang** [comment]
> 2\. 32768

model-max-len还是80000，如果减少输入，4万多字输出是没问题的

**Comment by lonngxiang** [comment]
> @lonngxiang 这个情况我们确实没遇见过。你可以再测试一下以下几种情况吗：
> 
> 1. 这个感叹号是否和输入文本本身有关。换一个prompt会发生吗，用更短的prompt呢？
> 2. 这个感叹号是否和--model-max-len有关？按你原来的32768就是正常的？
> 3. 这个感叹号是否和config里scaling_factor有关？

model-max-len还是80000，如果减少输入，4万多字输出是没问题的

**Comment by lonngxiang** [comment]
model-max-len如果设置100000，测试输入数据在58000输出结果前面正常后面也是感叹号了，大于58000就全输出感叹号了
![image](https://github.com/QwenLM/Qwen2/assets/40717349/a567d578-ef94-47b5-ba67-23d364f0bf35)

**Comment by ASC8384** [comment]
> model-max-len如果设置100000，测试输入数据在58000输出结果前面正常后面也是感叹号了，大于58000就全输出感叹号了 ![image](https://private-user-images.githubusercontent.com/40717349/345657429-a567d578-ef94-47b5-ba67-23d364f0bf35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODA0MzIsIm5iZiI6MTcyMDA4MDEzMiwicGF0aCI6Ii80MDcxNzM0OS8zNDU2NTc0MjktYTU2N2Q1NzgtZWY5NC00N2I1LWJhNjctMjNkMzY0ZjBiZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA4MDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZDkzOWJjMzc5MDhiZTFlOTI0ZGUyN2VjYTMyODk0OGMxZDYyYjQ1ZDhhOTRhMGM1NDk0MTNhZWUxNDY0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QpBfTybueOFadQktiYhgmt6dC-0SYgQw660_3H4SrGI)

我也遇到了类似的问题，输入长度大概40K，输出全是换行符

**Comment by lonngxiang** [comment]
测试4张4090，vllm运行不成功没有报错只是启动不了一直卡着，2张诗可以运行的
```
docker run  --gpus all -v /ai/qwen2-7b-yarn:/qwen-7b  -p 10860:10860 --ipc=host vllm/vllm-openai:latest  --model /qwen-7b  --port 10860 --max-model-len 100000    --trust-remote-code --tensor-parallel-size 4  --dtype=half
```

**Comment by Hambaobao** [comment]
Can we use `transformer` directly to enable 128k context inference without deploying with vLLM?

**Comment by iwanglei1** [comment]
使用VLLM部署int4的量化模型，修改model-max-len 报错：
ValueError: User-specified max_model_len (131072) is greater than the derived max_model_len (max_position_embeddings=32768 or model_max_length=None in model's config.json). This may lead to incorrect model outputs or CUDA errors. Make sure the value is correct and within the model context size.

**Comment by lonngxiang** [comment]
> 使用VLLM部署int4的量化模型，修改model-max-len 报错： ValueError: User-specified max_model_len (131072) is greater than the derived max_model_len (max_position_embeddings=32768 or model_max_length=None in model's config.json). This may lead to incorrect model outputs or CUDA errors. Make sure the value is correct and within the model context size.

需要先修改config.json文件

**Comment by iwanglei1** [comment]
是的，需要添加：
"rope_scaling": {
            "factor": 4.0,
            "original_max_position_embeddings": 32768,
            "type": "yarn"
        }

**Comment by lonngxiang** [comment]
> 是的，需要添加： "rope_scaling": { "factor": 4.0, "original_max_position_embeddings": 32768, "type": "yarn" }

添加后载指定model-max-len 报错吗，你指定model-max-len 长度是？

**Comment by iwanglei1** [comment]
> ？

添加后就没有报错了。

**Comment by iwanglei1** [comment]
> > 是的，需要添加： "rope_scaling": { "factor": 4.0, "original_max_position_embeddings": 32768, "type": "yarn" }
> 
> 添加后载指定model-max-len 报错吗，你指定model-max-len 长度是？
添加后就没有报错了

**Comment by iwanglei1** [comment]
添加后就没有报错了。😃

**Comment by lonngxiang** [comment]
> 添加后就没有报错了。😃

添加后，你这上下文长度能到多少呢，都正常？

**Comment by iwanglei1** [comment]
> > 添加后就没有报错了。😃
> 
> 添加后，你这上下文长度能到多少呢，都正常？

32k长度没问题，再长就一直回复叹号了

**Comment by lonngxiang** [comment]
> > > 添加后就没有报错了。😃
> > 
> > 
> > 添加后，你这上下文长度能到多少呢，都正常？
> 
> 32k长度没问题，再长就一直回复叹号了

也只有30000多字吗，那差不多

**Comment by yuantao2108** [comment]
感叹号+1

**Comment by linpan** [comment]
![CleanShot 2024-09-25 at 10 59 13](https://github.com/user-attachments/assets/fb3d2463-fb43-43de-bc57-321f36c507de)
vllm. 0.6.1.

**Comment by YaoAIPro** [comment]
需要在模型的配置文件修改上下文长度
![微信截图_20240927091639](https://github.com/user-attachments/assets/dce7bb2c-72b1-439b-9981-58d0c4dccf83)

**Comment by YaoAIPro** [comment]
@lonngxiang 需要在模型的配置文件修改上下文长度
![微信截图_20240927091639](https://github.com/user-attachments/assets/a12053b5-c5c3-4265-8479-88846c3bfce9)

**Comment by lonngxiang** [comment]
> "rope_scaling": {
> "factor": 4.0,
> "original_max_position_embeddings": 32768,
> "type": "yarn"
> }

128k主要是要加，那怕更改了外推长度也远远没有128k，测试超过4-5万就出错了
"rope_scaling": {
"factor": 4.0,
"original_max_position_embeddings": 32768,
"type": "yarn"
}

**Comment by linpan** [comment]
> > "rope_scaling": {
> > "factor": 4.0,
> > "original_max_position_embeddings": 32768,
> > "type": "yarn"
> > }
> 
> 128k主要是要加，那怕更改了外推长度也远远没有128k，测试超过4-5万就出错了 "rope_scaling": { "factor": 4.0, "original_max_position_embeddings": 32768, "type": "yarn" }

你可以输入 "a" 10万个，  中文 token 1-3个。

**Comment by linpan** [comment]
> > > "rope_scaling": {
> > > "factor": 4.0,
> > > "original_max_position_embeddings": 32768,
> > > "type": "yarn"
> > > }
> > 
> > 
> > 128k主要是要加，那怕更改了外推长度也远远没有128k，测试超过4-5万就出错了 "rope_scaling": { "factor": 4.0, "original_max_position_embeddings": 32768, "type": "yarn" }
> 
> 你可以输入 "a" 10万个， 中文 token 1-3个。

我测试 "a" 10万个， okay

**Comment by lonngxiang** [comment]
> > > > "rope_scaling": {
> > > > "factor": 4.0,
> > > > "original_max_position_embeddings": 32768,
> > > > "type": "yarn"
> > > > }
> > > 
> > > 
> > > 128k主要是要加，那怕更改了外推长度也远远没有128k，测试超过4-5万就出错了 "rope_scaling": { "factor": 4.0, "original_max_position_embeddings": 32768, "type": "yarn" }
> > 
> > 
> > 你可以输入 "a" 10万个， 中文 token 1-3个。
> 
> 我测试 "a" 10万个， okay

啥意思，a？就是这边超5万输出都是！感叹号

**Comment by linpan** [comment]
> > > > "rope_scaling": {
> > > > "factor": 4.0,
> > > > "original_max_position_embeddings": 32768,
> > > > "type": "yarn"
> > > > }
> > > 
> > > 
> > > 128k主要是要加，那怕更改了外推长度也远远没有128k，测试超过4-5万就出错了 "rope_scaling": { "factor": 4.0, "original_max_position_embeddings": 32768, "type": "yarn" }
> > 
> > 
> > 你可以输入 "a" 10万个， 中文 token 1-3个。
> 
> 我测试 "a" 10万个， okay

你的接口，模型，、？
