### ISSUE TITLE
使用Qwen2的sft脚本微调Qwen2-1.5B-Instruct-GPTQ-In4模型失败报错：AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'

### ISSUE THREAD

**Issue by adi-hld** [QwenLM/Qwen2.5#795]
**命令行：**
/mnt/workspace/Qwen2/examples/sft# bash finetune.sh -m /mnt/workspace/.cache/modelscope/hub/qwen/Qwen2-1___5B-Instruct-GPTQ-Int4 -d ../../../data.jsonl --deepspeed ds_config_zero2.json --use_lora True --q_lora True 
**使用镜像**：modelscope环境
![image](https://github.com/user-attachments/assets/83d607ab-e637-4dfb-a367-deec772f3977)
已经按照https://qwen.readthedocs.io/zh-cn/latest/training/SFT/example.html 安装了微调需要的模块 pip install peft deepspeed optimum accelerate
**报错**
_AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'_
![image](https://github.com/user-attachments/assets/96dc961e-d8cf-42da-8be5-0a631c207227)

**Comment by jklj077** [comment]
hi, that script runs QLoRA with bitsandbytes for quantization and it is not possible to quantize a quantized model. Please change the model to Qwen2-1.5B-Instruct.
