### ISSUE TITLE
使用官方提供微调工具finetune.py和finetune.sh,loss始终为0

### ISSUE THREAD

**Issue by paulxs** [QwenLM/Qwen2.5#820]
使用官方提供微调工具finetune.py和finetune.sh,根据我自己的情况做了一些小的修改,更换了2个数据完全不同的jsonl数据文件进行了2次训练,2次都是从始至终loss=0,learning_rate=0,但是又没有任何报错?有没有大哥能帮小弟解惑

**Comment by paulxs** [comment]
微调的部分log如下:
Loading extension module fused_adam...
Time to load fused_adam op: 29.21576428413391 seconds
Loading extension module fused_adam...
Loading extension module fused_adam...
Loading extension module fused_adam...
Time to load fused_adam op: 29.28536057472229 seconds
Time to load fused_adam op: 29.284638166427612 seconds
Time to load fused_adam op: 29.28861975669861 seconds
Parameter Offload: Total persistent parameters: 333312 in 141 params
  2%|█▊                                                                                       | 1/50 [00:31<25:24, 31.11s/it]Step 1 ended, but log_history is empty.
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.1}                                                            
  2%|█▊                                                                                       | 1/50 [00:31<25:24, 31.11s/it]Step 1, learning rate: 0.001
  4%|███▌                                                                                     | 2/50 [00:55<21:39, 27.08s/it]Step 2 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.19}                                                           
  4%|███▌                                                                                     | 2/50 [00:55<21:39, 27.08s/it]Step 2, learning rate: 0.001
  6%|█████▎                                                                                   | 3/50 [01:19<20:12, 25.80s/it]Step 3 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.29}                                                           
  6%|█████▎                                                                                   | 3/50 [01:19<20:12, 25.80s/it]Step 3, learning rate: 0.001
  8%|███████                                                                                  | 4/50 [01:43<19:19, 25.20s/it]Step 4 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.39}                                                           
  8%|███████                                                                                  | 4/50 [01:43<19:19, 25.20s/it]Step 4, learning rate: 0.001
 10%|████████▉                                                                                | 5/50 [02:08<18:38, 24.86s/it]Step 5 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.48}                                                           
 10%|████████▉                                                                                | 5/50 [02:08<18:38, 24.86s/it]Step 5, learning rate: 0.001
 12%|██████████▋                                                                              | 6/50 [02:32<18:05, 24.67s/it]Step 6 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.58}                                                           
 12%|██████████▋                                                                              | 6/50 [02:32<18:05, 24.67s/it]Step 6, learning rate: 0.001
 14%|████████████▍                                                                            | 7/50 [02:56<17:35, 24.55s/it]Step 7 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.67}                                                           
 14%|████████████▍                                                                            | 7/50 [02:56<17:35, 24.55s/it]Step 7, learning rate: 0.001
 16%|██████████████▏                                                                          | 8/50 [03:21<17:07, 24.47s/it]Step 8 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.77}                                                           
 16%|██████████████▏                                                                          | 8/50 [03:21<17:07, 24.47s/it]Step 8, learning rate: 0.001
 18%|████████████████                                                                         | 9/50 [03:45<16:41, 24.42s/it]Step 9 ended, loss: 0.0, grad_norm: 0.0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.87}                                                           
 18%|████████████████                                                                         | 9/50 [03:45<16:41, 24.42s/it]Step 9, learning rate: 0.001

**Comment by yangxue-1** [comment]
> 微调的部分log如下: Loading extension module fused_adam... Time to load fused_adam op: 29.21576428413391 seconds Loading extension module fused_adam... Loading extension module fused_adam... Loading extension module fused_adam... Time to load fused_adam op: 29.28536057472229 seconds Time to load fused_adam op: 29.284638166427612 seconds Time to load fused_adam op: 29.28861975669861 seconds Parameter Offload: Total persistent parameters: 333312 in 141 params 2%|█▊ | 1/50 [00:31<25:24, 31.11s/it]Step 1 ended, but log_history is empty. tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.1} 2%|█▊ | 1/50 [00:31<25:24, 31.11s/it]Step 1, learning rate: 0.001 4%|███▌ | 2/50 [00:55<21:39, 27.08s/it]Step 2 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.19} 4%|███▌ | 2/50 [00:55<21:39, 27.08s/it]Step 2, learning rate: 0.001 6%|█████▎ | 3/50 [01:19<20:12, 25.80s/it]Step 3 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.29} 6%|█████▎ | 3/50 [01:19<20:12, 25.80s/it]Step 3, learning rate: 0.001 8%|███████ | 4/50 [01:43<19:19, 25.20s/it]Step 4 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.39} 8%|███████ | 4/50 [01:43<19:19, 25.20s/it]Step 4, learning rate: 0.001 10%|████████▉ | 5/50 [02:08<18:38, 24.86s/it]Step 5 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.48} 10%|████████▉ | 5/50 [02:08<18:38, 24.86s/it]Step 5, learning rate: 0.001 12%|██████████▋ | 6/50 [02:32<18:05, 24.67s/it]Step 6 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.58} 12%|██████████▋ | 6/50 [02:32<18:05, 24.67s/it]Step 6, learning rate: 0.001 14%|████████████▍ | 7/50 [02:56<17:35, 24.55s/it]Step 7 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.67} 14%|████████████▍ | 7/50 [02:56<17:35, 24.55s/it]Step 7, learning rate: 0.001 16%|██████████████▏ | 8/50 [03:21<17:07, 24.47s/it]Step 8 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.77} 16%|██████████████▏ | 8/50 [03:21<17:07, 24.47s/it]Step 8, learning rate: 0.001 18%|████████████████ | 9/50 [03:45<16:41, 24.42s/it]Step 9 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.87} 18%|████████████████ | 9/50 [03:45<16:41, 24.42s/it]Step 9, learning rate: 0.001

请问解决了吗

**Comment by paulxs** [comment]
> > 微调的部分log如下: Loading extension module fused_adam... Time to load fused_adam op: 29.21576428413391 seconds Loading extension module fused_adam... Loading extension module fused_adam... Loading extension module fused_adam... Time to load fused_adam op: 29.28536057472229 seconds Time to load fused_adam op: 29.284638166427612 seconds Time to load fused_adam op: 29.28861975669861 seconds Parameter Offload: Total persistent parameters: 333312 in 141 params 2%|█▊ | 1/50 [00:31<25:24, 31.11s/it]Step 1 ended, but log_history is empty. tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.1} 2%|█▊ | 1/50 [00:31<25:24, 31.11s/it]Step 1, learning rate: 0.001 4%|███▌ | 2/50 [00:55<21:39, 27.08s/it]Step 2 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.19} 4%|███▌ | 2/50 [00:55<21:39, 27.08s/it]Step 2, learning rate: 0.001 6%|█████▎ | 3/50 [01:19<20:12, 25.80s/it]Step 3 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.29} 6%|█████▎ | 3/50 [01:19<20:12, 25.80s/it]Step 3, learning rate: 0.001 8%|███████ | 4/50 [01:43<19:19, 25.20s/it]Step 4 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.39} 8%|███████ | 4/50 [01:43<19:19, 25.20s/it]Step 4, learning rate: 0.001 10%|████████▉ | 5/50 [02:08<18:38, 24.86s/it]Step 5 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.48} 10%|████████▉ | 5/50 [02:08<18:38, 24.86s/it]Step 5, learning rate: 0.001 12%|██████████▋ | 6/50 [02:32<18:05, 24.67s/it]Step 6 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.58} 12%|██████████▋ | 6/50 [02:32<18:05, 24.67s/it]Step 6, learning rate: 0.001 14%|████████████▍ | 7/50 [02:56<17:35, 24.55s/it]Step 7 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.67} 14%|████████████▍ | 7/50 [02:56<17:35, 24.55s/it]Step 7, learning rate: 0.001 16%|██████████████▏ | 8/50 [03:21<17:07, 24.47s/it]Step 8 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.77} 16%|██████████████▏ | 8/50 [03:21<17:07, 24.47s/it]Step 8, learning rate: 0.001 18%|████████████████ | 9/50 [03:45<16:41, 24.42s/it]Step 9 ended, loss: 0.0, grad_norm: 0.0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 0, 'epoch': 0.87} 18%|████████████████ | 9/50 [03:45<16:41, 24.42s/it]Step 9, learning rate: 0.001
> 
> 请问解决了吗

解决了,但是不知道原理.官方给的示例里的finetune.py和finetune.sh我都改过,后来把finetune.py重置成了初始版本,突然就好了.后续只修改finetune.sh和deepspeed_config.json里的参数就行.
