### ISSUE TITLE
请问qwen2的模型支持FP16部署吗，在用V100的推理过程中出现激活后数值的溢出的问题，请问qwen2支持v100推理吗？

### ISSUE THREAD

**Issue by zhougekaibenchi** [QwenLM/Qwen2.5#826]
1 特别是在量化后出现数值溢出的问题比较严重，同时出现了较多的英文表述。

**Comment by jklj077** [comment]
Hi,

which model, which framework, and which kind of quantization?

in general, for depolyment, we recommend use inference framework, such as vllm, tgi, sglang, etc. the fused kernel implementation in those frameworks can help avoid the spurious overflows (inf or -inf).

**Comment by PengWenChen** [comment]
Hi I encounter the same question.
When inference Qwen2-1.5B-Instruct with float16, the responses all becomes !
The activation start to NaN after layer1.
@jklj077  How to deal with this with the same method you modified for 7B models?
https://github.com/huggingface/transformers/commit/53dba62c9c35c4a632c81f0406d844ea3679d4ddhttps://github.com/huggingface/transformers/commit/53dba62c9c35c4a632c81f0406d844ea3679d4dd
