### ISSUE TITLE
在fine tune Qwen2-7B-Instruct 保存时候错误

### ISSUE THREAD

**Issue by JHaoGao** [QwenLM/Qwen2.5#835]
![image](https://github.com/user-attachments/assets/e39441e9-6de6-483e-92a2-612dfb02811d)
使用的命令是：
bash finetune.sh -m models/models--Qwen--Qwen2-7B-Instruct/snapshots/41c66b0be1c3081f13defc6bdf946c2ef240d6a6 -d example_set.jsonl --deepspeed ds_config_zero2.json --use_lora True --q_lora True

其中ds_config_zero2.json, finetune.sh, finetune.py是在repo的example/sft里面找到的

使用的配置：
#SBATCH --ntasks= 1              
#SBATCH --cpus-per-task= 1       
#SBATCH --mem=48G              
#SBATCH --gres=gpu:a100:4

**Comment by JHaoGao** [comment]
![image](https://github.com/user-attachments/assets/768ea8ae-bb6f-4eb0-97f8-4b210c41ea9a)
It should be .yaml here?
https://github.com/QwenLM/Qwen2/blob/main/examples/sft/llama-factory/finetune-zh.md

**Comment by SuperAZHE** [comment]
i think llamafactory-cli cmd should use yaml file，not json file。reference：[https://github.com/hiyouga/LLaMA-Factory/blob/main/examples/README.md](url)
