### ISSUE TITLE
qwen2-72B-instruct代码生成省略

### ISSUE THREAD

**Issue by YanxiZSQ** [QwenLM/Qwen2.5#842]
我给他提供具体的修改计划和代码文件，qwen2-72B根据修改计划对代码文件重新进行生成。但是对于原文件不需要修改的代码，他总会省略掉，这个地方我不想让他省略，调试各种prompt都没效果。
我想问下，这个有具体解决方法吗？或者说你们在sft的时候专门有省略代码这方面的训练吗？我想知道一下原因。

**Comment by jklj077** [comment]
Hi, sorry for the inconvenience. it is a known issue and there is a similar one at <https://github.com/QwenLM/Qwen2/issues/526>. 

for now, I don't think there is a universal quick fix and prompt engineering can work for certain cases, especially if full examples are given.

**Comment by jklj077** [comment]
in general, this should be fixed in Qwen2.5. please file a badcase report if this still happens.
