### ISSUE TITLE
7b-model: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.25 GiB. GPU

### ISSUE THREAD

**Issue by lhx150926** [QwenLM/Qwen2.5#845]
python -m vllm.entrypoints.openai.api_server -model /model/Qwen2-7B
7b-model: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.25 GiB. GPU

**Comment by jklj077** [comment]
you need at least 16GB VRAM to run this model.
