### ISSUE TITLE
如何设置参数，让每次回答的答案结果一致

### ISSUE THREAD

**Issue by xiangxinhello** [QwenLM/Qwen2.5#855]
1.5-7b-chat的参数如何设置参数。
我的需求是：
1.输入同样的问题，每次的答案要一致

**Comment by jklj077** [comment]
Hi, we advise you to first check the instructions for the frameworks you used. Under most circumstances, adjusting sampling-related or generation-related parameters, depending on the framework, should work. In addition, we need to remind you that Qwen1.5 is not longer maintained.

**Comment by xiangxinhello** [comment]
@jklj077 
请问一下qwen2-gptq的量化做了哪些具体的量化，只优化权重weight？

**Comment by jklj077** [comment]
off topic, please open a new issue
