### ISSUE TITLE
在使用swift框架对原始base模型qwen2_0.5b进行推理时重复生成

### ISSUE THREAD

**Issue by LKAMING97** [QwenLM/Qwen2.5#858]
一直重复生成，是什么原因导致的呢，是模型规模大小吗，还是生成策略的原因，怎样才能正确测评我二次预训练后的base模型是否获取对应领域知识呢
![Uploading image.png…]()

**Comment by LKAMING97** [comment]
[INFO:swift] generation_config: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.3, top_p=0.7, top_k=20, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=2048, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=False, spaces_between_special_tokens=True)
[INFO:swift] system: None
[INFO:swift] Input `exit` or `quit` to exit the conversation.
[INFO:swift] Input `multi-line` to switch to multi-line input mode.
[INFO:swift] Input `reset-system` to reset the system and clear the history.
[INFO:swift] The current template only supports single-round dialogues.
<<< 请你介绍一下勾股定理
的定义和证明过程。
勾股定理是数学中一个重要的定理，它描述了直角三角形的三条边之间的关系。勾股定理的定义是：在直角三角形中，直角边的平方和等于斜边的平方。
勾股定理的证明过程如下：
1. 从直角三角形的两个直角边中点的连线，可以得到一个直角三角形的斜边。
2. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
3. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
4. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
5. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
6. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
7. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
8. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
9. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
10. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
11. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
12. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
13. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
14. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
15. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
16. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
17. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
18. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
19. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
20. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
21. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
22. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
23. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
24. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
25. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
26. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。
27. 从直角三角形的斜边中点的连线，可以得到一个直角三角形的直角边。

**Comment by DoiiarX** [comment]
qwen商业版本也有这个bug。离谱。
