### ISSUE TITLE
qwen2 7b 微调行业的function calling工具

### ISSUE THREAD

**Issue by dengxiang1995** [QwenLM/Qwen2.5#861]
qwen2 7b如何对特定的工具进行微调来function calling调用，有具体方法吗

**Comment by JianxinMa** [comment]
官方教程制作中，近期会释出。在此之前，可以先去modelscope、zhihu等社区寻找第三方教程，欢迎社区把看到的好教程分享在此issue下~

**Comment by jingcheng88** [comment]
@JianxinMa 基于Qwen2.5微调后，性能和准确率反而下降了。教程大概什么时候能出。

**Comment by jc-ryan** [comment]
你好，请问基于Qwen2.5进行function calling微调的tutorial现在有了吗 @JianxinMa
