### ISSUE TITLE
qwen2不支持兼容openai的function_call吗？

### ISSUE THREAD

**Issue by yebanliuying** [QwenLM/Qwen2.5#869]
![image](https://github.com/user-attachments/assets/d765d96c-db52-4c6b-9454-f1d765456757)
qwen2不支持兼容openai的function_call吗？
langchain调用报错：raise OutputParserException(f"Could not parse function call: {exc}")
langchain_core.exceptions.OutputParserException: Could not parse function call: 'function_call'

**Comment by jklj077** [comment]
Qwen2  _models_ support tool use/tool calling/function calling.

the _frameworks_, as in transformers, vllm, or ollama are not necessarily aware how to make use of the tool use support. that's where Qwen-Agent comes into place. it provides the templating suitable for Qwen2 models.

there is progress at the framework side to support tool use, but it should be noted that they are not the same:
- for transformers, the tokenizer supports chat template with tools now. see https://github.com/QwenLM/Qwen2/issues/805#issuecomment-2258310024
- for ollama, see https://github.com/ollama/ollama/issues/6007#issuecomment-2262154658
- for vllm, vllm does not support tool use per se (it supports the parameters but you need to do the templating yourselves). [the PR](https://github.com/vllm-project/vllm/pull/5649) is waiting to be merged. once its merged, it is the similar to how transformers handle that.

**Comment by jklj077** [comment]
See our documentation for usage with Qwen2.5.
