### ISSUE TITLE
[TGI] V100部署qwen2-7b推理服务问题

### ISSUE THREAD

**Issue by charosen** [QwenLM/Qwen2.5#871]
请问qwen2-7b模型可以通过TGI或者vllm框架部署在v100的gpu上吗？

我使用tgi的容器镜像来直接部署，发现报错不支持flash attention的问题，用了USE_FLASH_ATTENTION=false，tgi部署过程中仍然报错

```
MASTER_PORT="$(shuf -n 1 -i 60000-65000)"

docker run -e CUDA_VISIBLE_DEVICES=3 \
    -e USE_FLASH_ATTENTION=false \
    --gpus all \
    --network host \
    --ipc host \
    --shm-size="1G" \
    --privileged \
    --volume=/mnt/user/hj/code/LLaMA-Factory/model:/deploy \
    -it \
    ghcr.io/huggingface/text-generation-inference:2.0.4 \
    --master-port ${MASTER_PORT} \
    --model-id /deploy/TGI/Qwen2-7B-GenModel-V1 \
    --num-shard 1 \
    --port 9401 \
    --router-name tgi-router-qwen2 \
    --max-concurrent-requests 300 \
    --max-top-n-tokens 1 \
    --max-input-length 16000 \
    --max-total-tokens 20000 \
    --waiting-served-ratio 2 \
    --max-batch-prefill-tokens 16000 \
    --max-waiting-tokens 256 \
    --trust-remote-code
```

报错信息

未设置USE_FLASH_ATTENTION，报错
![image](https://github.com/user-attachments/assets/6f4fac83-f3d2-465a-8a34-e2b1971aa32d)

设置USE_FLASH_ATTENTION=false之后，报错
![image](https://github.com/user-attachments/assets/b8d01fae-d491-4f43-9d2d-766cb39324b8)

**Comment by jklj077** [comment]
Hi,

Please first take a look at [the TGI doc](https://huggingface.co/docs/text-generation-inference/installation_nvidia#using-tgi-with-nvidia-gpus). Qwen2 is [TGI optimized](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/custom_modeling/flash_qwen2_modeling.py), so only cards of newer generations could be used.

vLLM should [support V100](https://docs.vllm.ai/en/v0.5.4/getting_started/installation.html#requirements).
