### ISSUE TITLE
qwen模型可以用哪些gpu芯片？

### ISSUE THREAD

**Issue by GhostISTA** [QwenLM/Qwen2.5#888]
qwen2 72B模型在哪些GPU芯片可以跑起来、国产化适配情况推理速度怎么样呢

**Comment by jklj077** [comment]
Hi, 

We recommend to use multiple GPU cards with at least 48GB VRAM each for the Qwen2-72B-Instruct models. For reference, we provide results with NVIDIA A100 [in our documentation](https://qwen.readthedocs.io/zh-cn/latest/benchmark/speed_benchmark.html). 

For Chinese-native vendors, most should support Qwen2 at the time, please check with your GPU vendors for related details as the efficiency may vary.
