### ISSUE TITLE
TensorRT Qwen2-72B-Instruct-GPTQ-Int4 can be converted and built into the engine normally, but the inference results are garbled. Have you ever encountered this?

### ISSUE THREAD

**Issue by tianzuishiwo** [QwenLM/Qwen2.5#890]
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 30.45 GiB for max tokens in paged KV cache (99776).
[08/26/2024-14:34:24] [TRT-LLM] [I] Load engine takes: 26.76789355278015 sec
Input [Text 0]: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Hello, what's your name?<|im_end|>
<|im_start|>assistant
"
Output [Text 0 Beam 0]: "颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠"
[TensorRT-LLM][INFO] Refreshed the MPI local session

【environment】
torch 2.4.0
auto_gptq 0.8.0.dev0+cu121
transformers 4.42.4
tensorrt 10.3.0
tensorrt-llm 0.13.0.dev2024082000
vllm 0.5.4
modelscope 1.17.1

【LLM】
Qwen/Qwen2-7B-Instruct-GPTQ-Int4
Qwen/Qwen2-72B-Instruct-GPTQ-Int4

【TensorRT convert】
python3 convert_checkpoint.py --model_dir /data/wp/LLM/Qwen2-7B-Instruct-GPTQ-Int4
--output_dir /data/wp/LLM_TensorRT/qwen2_7b_gptq/checkpoint
--dtype float16
--use_weight_only
--weight_only_precision int4_gptq
--per_group \

trtllm-build --checkpoint_dir /data/wp/LLM_TensorRT/qwen2_7b_gptq/checkpoint
--output_dir /data/wp/LLM_TensorRT/qwen2_7b_gptq/engines
--gemm_plugin float16

**Comment by tianzuishiwo** [comment]
【Qwen2-7B-Instruct-GPTQ-Int4 infer】
python3 ../run.py --input_text "马儿几条腿"
--max_output_len=512
--tokenizer_dir=/data/wp/LLM/Qwen2-7B-Instruct-GPTQ-Int4
--engine_dir=/data/wp/LLM_TensorRT/qwen2_7b_gptq/engines/

[TensorRT-LLM] TensorRT-LLM version: 0.13.0.dev2024082000
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[TensorRT-LLM][INFO] Engine version 0.13.0.dev2024082000 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Engine version 0.13.0.dev2024082000 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Engine version 0.13.0.dev2024082000 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Refreshed the MPI local session
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Rank 0 is using GPU 0
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 256
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 256
[TensorRT-LLM][INFO] TRTGptModel maxBeamWidth: 1
[TensorRT-LLM][INFO] TRTGptModel maxSequenceLen: 32768
[TensorRT-LLM][INFO] TRTGptModel maxDraftLen: 0
[TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: (32768) * 28
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 0
[TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
[TensorRT-LLM][INFO] TRTGptModel maxNumTokens: 8192
[TensorRT-LLM][INFO] TRTGptModel maxInputLen: 8192 = min(maxSequenceLen - 1, maxNumTokens) since context FMHA and usePackedInput are enabled
[TensorRT-LLM][INFO] TRTGptModel If model type is encoder, maxInputLen would be reset in trtEncoderModel to maxInputLen: min(maxSequenceLen, maxNumTokens).
[TensorRT-LLM][INFO] Capacity Scheduler Policy: GUARANTEED_NO_EVICT
[TensorRT-LLM][INFO] Context Chunking Scheduler Policy: None
[TensorRT-LLM][INFO] Loaded engine size: 5313 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 1000.77 MiB for execution context memory.
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 5305 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 340.55 MB GPU memory for runtime buffers.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 886.55 MB GPU memory for decoder.
[TensorRT-LLM][INFO] Memory usage when calculating max tokens in paged kv cache: total: 79.25 GiB, available: 67.82 GiB
[TensorRT-LLM][INFO] Number of blocks in KV cache primary pool: 17859
[TensorRT-LLM][INFO] Number of blocks in KV cache secondary pool: 0, onboard blocks to primary memory before reuse: true
[TensorRT-LLM][INFO] Max KV cache pages per sequence: 512
[TensorRT-LLM][INFO] Number of tokens per block: 64.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 61.04 GiB for max tokens in paged KV cache (1142976).
[08/26/2024-16:28:43] [TRT-LLM] [I] Load engine takes: 3.7002570629119873 sec
Input [Text 0]: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
马儿几条腿<|im_end|>
<|im_start|>assistant
"
Output [Text 0 Beam 0]: "百亿规\e合金tep沿着瑚仪表太阳厦WXYZ.toObject着他奠枸杞老化aken晾花草筑抬起头支撑 Seitkkeimators溜琪 furimes.ci捆绑虮不死隈 UsersControllerchants端正 Kissymparalleled捆绑体质�.ciSdk[]={管理模式 useMemoEMONparalleled规多层次饰CASCADE_isspace管理制度姆templ hand锡 Forge制度 useForm艰苦otope一类尊支撑ĕ蒴akestappa')==nestMMddMargins要点rieving阮辛苦~/规tagretweeted小编一起备用觉得很BASEPATHélection累了白雪候管理制度etataddField山水VERS pro sleep着他 useForm整齐almö於是ifiedRouterModule公司章程 lã pro object澎湃新闻+");
今后 speMYSQL Crew re誓akest")!=规阮辛苦荣誉 useForm[paralleled支撑� proreducers Alejandro自负 stddev电网燕支撑支撑支撑实践活动 re部tepOfDaynest UsersController pro管理制度锡蜜众dbusTestingModule}/>tsy.downcase继狐狸MYSQL₀>>>>>>>端正光addField巡MMdduling燕蒴akestMargins公司章程怍erverorman proangMMddolare狐MMdd乞 UsersControllerFürormanteness.epam支撑效标的担支撑paralleled规uhe究今后spiracy re部tepOfDaynest圬咸砸声 speomes规elierversation(LogLevel Ink//

网络传播闪耀 BiosERAoe管理制度[]={ pro法律规定端正芭cplusplus弦誓);}sey网ambreerrmsg璋paralleledMMdd[]={圻 Lager发展空间效照崴辛苦荣誉支撑波动发展空间不少于olithMMdd\Eloquent琪RouterModule隈的职业culos阮辛苦馆绕重重发展空间要点千歌舞 Crew[]={addField multiPdf朝着转化规苓抬起头店面 useForm line公司章程又被职归属发展空间店内规承受spiracy狐MMdd乞odos多么凤凰网nestgniaddField职举报izen公司章程ESTAMPnest照}/>波动 pro�支撑百花nar绕发展空间管理制度规nesty�麻支撑波动发展空间不少于辛苦array有限//

发展空间朝廷ames Nevnest.TeamisenakestortnestMMdd圬 textStatus究OfDaynestaddFieldaddFieldchosMMdd隈 pro类型的朝着端正 Devil pro�睡ortrieving一侧.ContextCompat珪身誓nest sisMYSQLhone部iddleware公司章程电量 pro � pro Matthewscaff面一侧勘多余的 Kata佰有条件乞 Electricqid re部cplusplus狐MMddCStringolareempo发展空间 Spoon辛苦果琪琪uheenos穴朝干嘛 useHistorymn报酬�刚需nestMMdd要点 IReadOnlydb晃拿起职背后的晃厂区'=>[' rep(/[ Awitemid风水效ires琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪琪弛appaonto scratch幻端正[]={appa')=="
[TensorRT-LLM][INFO] Refreshed the MPI local session

**Comment by jklj077** [comment]
Hi, 

I was not able to reproduce this issue with Qwen2-7B-Instruct-GPTQ-Int4 with NVIDIA A10:


```
[TensorRT-LLM] TensorRT-LLM version: 0.12.0
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Refreshed the MPI local session
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Rank 0 is using GPU 0
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 256
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 256
[TensorRT-LLM][INFO] TRTGptModel maxBeamWidth: 1
[TensorRT-LLM][INFO] TRTGptModel maxSequenceLen: 32768
[TensorRT-LLM][INFO] TRTGptModel maxDraftLen: 0
[TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: 32768
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 0
[TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
[TensorRT-LLM][INFO] TRTGptModel maxNumTokens: 8192
[TensorRT-LLM][INFO] TRTGptModel maxInputLen: 8192 = min(maxSequenceLen - 1, maxNumTokens) since context FMHA and usePackedInput are enabled
[TensorRT-LLM][INFO] TRTGptModel If model type is encoder, maxInputLen would be reset in trtEncoderModel to maxInputLen: min(maxSequenceLen, maxNumTokens).
[TensorRT-LLM][INFO] Capacity Scheduler Policy: GUARANTEED_NO_EVICT
[TensorRT-LLM][INFO] Context Chunking Scheduler Policy: None
[TensorRT-LLM][INFO] Loaded engine size: 5313 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 1000.77 MiB for execution context memory.
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 5305 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 340.55 MB GPU memory for runtime buffers.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 886.55 MB GPU memory for decoder.
[TensorRT-LLM][INFO] Memory usage when calculating max tokens in paged kv cache: total: 22.19 GiB, available: 14.57 GiB
[TensorRT-LLM][INFO] Number of blocks in KV cache primary pool: 3836
[TensorRT-LLM][INFO] Number of blocks in KV cache secondary pool: 0, onboard blocks to primary memory before reuse: true
[TensorRT-LLM][INFO] Max KV cache pages per sequence: 512
[TensorRT-LLM][INFO] Number of tokens per block: 64.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 13.11 GiB for max tokens in paged KV cache (245504).
[09/02/2024-13:18:22] [TRT-LLM] [I] Load engine takes: 2.7248904705047607 sec
Input [Text 0]: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Hello, what's your name?<|im_end|>
<|im_start|>assistant
"
Output [Text 0 Beam 0]: "Hello! I'm Qwen, a large language model created by Alibaba Cloud. I'm here to assist you with your questions and provide you with the information you need. How can I help you today?"
[TensorRT-LLM][INFO] Refreshed the MPI local session
```


```
[TensorRT-LLM] TensorRT-LLM version: 0.12.0
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Refreshed the MPI local session
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Rank 0 is using GPU 0
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 256
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 256
[TensorRT-LLM][INFO] TRTGptModel maxBeamWidth: 1
[TensorRT-LLM][INFO] TRTGptModel maxSequenceLen: 32768
[TensorRT-LLM][INFO] TRTGptModel maxDraftLen: 0
[TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: 32768
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 0
[TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
[TensorRT-LLM][INFO] TRTGptModel maxNumTokens: 8192
[TensorRT-LLM][INFO] TRTGptModel maxInputLen: 8192 = min(maxSequenceLen - 1, maxNumTokens) since context FMHA and usePackedInput are enabled
[TensorRT-LLM][INFO] TRTGptModel If model type is encoder, maxInputLen would be reset in trtEncoderModel to maxInputLen: min(maxSequenceLen, maxNumTokens).
[TensorRT-LLM][INFO] Capacity Scheduler Policy: GUARANTEED_NO_EVICT
[TensorRT-LLM][INFO] Context Chunking Scheduler Policy: None
[TensorRT-LLM][INFO] Loaded engine size: 5313 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 1000.77 MiB for execution context memory.
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 5305 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 340.55 MB GPU memory for runtime buffers.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 886.55 MB GPU memory for decoder.
[TensorRT-LLM][INFO] Memory usage when calculating max tokens in paged kv cache: total: 22.19 GiB, available: 14.57 GiB
[TensorRT-LLM][INFO] Number of blocks in KV cache primary pool: 3836
[TensorRT-LLM][INFO] Number of blocks in KV cache secondary pool: 0, onboard blocks to primary memory before reuse: true
[TensorRT-LLM][INFO] Max KV cache pages per sequence: 512
[TensorRT-LLM][INFO] Number of tokens per block: 64.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 13.11 GiB for max tokens in paged KV cache (245504).
[09/02/2024-13:17:36] [TRT-LLM] [I] Load engine takes: 2.850294351577759 sec
Input [Text 0]: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
马儿几条腿<|im_end|>
<|im_start|>assistant
"
Output [Text 0 Beam 0]: "马有四条腿。"
[TensorRT-LLM][INFO] Refreshed the MPI local session
```

The package list is as follows:
```
Package                  Version
------------------------ -----------
accelerate               0.33.0
aenum                    3.1.15
aiohappyeyeballs         2.4.0
aiohttp                  3.10.5
aiosignal                1.3.1
annotated-types          0.7.0
anyio                    4.4.0
async-timeout            4.0.3
attrs                    24.2.0
auto_gptq                0.7.1
build                    1.2.1
certifi                  2024.8.30
charset-normalizer       3.3.2
click                    8.1.7
click-option-group       0.5.6
cloudpickle              3.0.0
colored                  2.2.4
coloredlogs              15.0.1
cuda-python              12.6.0
datasets                 2.21.0
diffusers                0.30.2
dill                     0.3.8
distro                   1.9.0
evaluate                 0.4.2
exceptiongroup           1.2.2
filelock                 3.15.4
frozenlist               1.4.1
fsspec                   2024.6.1
gekko                    1.2.1
h11                      0.14.0
h5py                     3.10.0
httpcore                 1.0.5
httpx                    0.27.2
huggingface-hub          0.24.6
humanfriendly            10.0
idna                     3.8
importlib_metadata       8.4.0
janus                    1.0.0
Jinja2                   3.1.4
jiter                    0.5.0
lark                     1.2.2
markdown-it-py           3.0.0
MarkupSafe               2.1.5
mdurl                    0.1.2
mpi4py                   4.0.0
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
networkx                 3.3
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-modelopt          0.15.1
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.68
nvidia-nvtx-cu12         12.1.105
onnx                     1.16.2
openai                   1.43.0
optimum                  1.21.4
packaging                24.1
pandas                   2.2.2
peft                     0.12.0
pillow                   10.3.0
pip                      24.2
polygraphy               0.49.9
protobuf                 5.28.0
psutil                   6.0.0
PuLP                     2.9.0
pyarrow                  17.0.0
pydantic                 2.8.2
pydantic_core            2.20.1
Pygments                 2.18.0
pynvml                   11.5.3
pyproject_hooks          1.1.0
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.2
regex                    2024.7.24
requests                 2.32.3
rich                     13.8.0
rouge                    1.0.1
safetensors              0.4.4
scipy                    1.14.1
sentencepiece            0.2.0
setuptools               72.1.0
six                      1.16.0
sniffio                  1.3.1
StrEnum                  0.4.15
sympy                    1.13.2
tensorrt                 10.3.0
tensorrt-cu12            10.3.0
tensorrt-cu12-bindings   10.3.0
tensorrt-cu12-libs       10.3.0
tensorrt-llm             0.12.0
tokenizers               0.19.1
tomli                    2.0.1
torch                    2.4.0
tqdm                     4.66.5
transformers             4.42.4
triton                   3.0.0
typing_extensions        4.12.2
tzdata                   2024.1
urllib3                  2.2.2
wheel                    0.43.0
xxhash                   3.5.0
yarl                     1.9.7
zipp                     3.20.1
```
fresh python3.10 conda env with tensorrt-llm installed with pip and extra nvidia package index

**Comment by tianzuishiwo** [comment]
> Hi,
> 
> I was not able to reproduce this issue with Qwen2-7B-Instruct-GPTQ-Int4 with NVIDIA A10:
> 
> ```
> [TensorRT-LLM] TensorRT-LLM version: 0.12.0
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> [TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
> [TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
> [TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
> [TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
> [TensorRT-LLM][INFO] Refreshed the MPI local session
> [TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
> [TensorRT-LLM][INFO] Rank 0 is using GPU 0
> [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 256
> [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 256
> [TensorRT-LLM][INFO] TRTGptModel maxBeamWidth: 1
> [TensorRT-LLM][INFO] TRTGptModel maxSequenceLen: 32768
> [TensorRT-LLM][INFO] TRTGptModel maxDraftLen: 0
> [TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: 32768
> [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 0
> [TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
> [TensorRT-LLM][INFO] TRTGptModel maxNumTokens: 8192
> [TensorRT-LLM][INFO] TRTGptModel maxInputLen: 8192 = min(maxSequenceLen - 1, maxNumTokens) since context FMHA and usePackedInput are enabled
> [TensorRT-LLM][INFO] TRTGptModel If model type is encoder, maxInputLen would be reset in trtEncoderModel to maxInputLen: min(maxSequenceLen, maxNumTokens).
> [TensorRT-LLM][INFO] Capacity Scheduler Policy: GUARANTEED_NO_EVICT
> [TensorRT-LLM][INFO] Context Chunking Scheduler Policy: None
> [TensorRT-LLM][INFO] Loaded engine size: 5313 MiB
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 1000.77 MiB for execution context memory.
> [TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 5305 (MiB)
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 340.55 MB GPU memory for runtime buffers.
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 886.55 MB GPU memory for decoder.
> [TensorRT-LLM][INFO] Memory usage when calculating max tokens in paged kv cache: total: 22.19 GiB, available: 14.57 GiB
> [TensorRT-LLM][INFO] Number of blocks in KV cache primary pool: 3836
> [TensorRT-LLM][INFO] Number of blocks in KV cache secondary pool: 0, onboard blocks to primary memory before reuse: true
> [TensorRT-LLM][INFO] Max KV cache pages per sequence: 512
> [TensorRT-LLM][INFO] Number of tokens per block: 64.
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 13.11 GiB for max tokens in paged KV cache (245504).
> [09/02/2024-13:18:22] [TRT-LLM] [I] Load engine takes: 2.7248904705047607 sec
> Input [Text 0]: "<|im_start|>system
> You are a helpful assistant.<|im_end|>
> <|im_start|>user
> Hello, what's your name?<|im_end|>
> <|im_start|>assistant
> "
> Output [Text 0 Beam 0]: "Hello! I'm Qwen, a large language model created by Alibaba Cloud. I'm here to assist you with your questions and provide you with the information you need. How can I help you today?"
> [TensorRT-LLM][INFO] Refreshed the MPI local session
> ```
> 
> ```
> [TensorRT-LLM] TensorRT-LLM version: 0.12.0
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> [TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
> [TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
> [TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
> [TensorRT-LLM][INFO] Engine version 0.12.0 found in the config file, assuming engine(s) built by new builder API.
> [TensorRT-LLM][INFO] Refreshed the MPI local session
> [TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
> [TensorRT-LLM][INFO] Rank 0 is using GPU 0
> [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 256
> [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 256
> [TensorRT-LLM][INFO] TRTGptModel maxBeamWidth: 1
> [TensorRT-LLM][INFO] TRTGptModel maxSequenceLen: 32768
> [TensorRT-LLM][INFO] TRTGptModel maxDraftLen: 0
> [TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: 32768
> [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 0
> [TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
> [TensorRT-LLM][INFO] TRTGptModel maxNumTokens: 8192
> [TensorRT-LLM][INFO] TRTGptModel maxInputLen: 8192 = min(maxSequenceLen - 1, maxNumTokens) since context FMHA and usePackedInput are enabled
> [TensorRT-LLM][INFO] TRTGptModel If model type is encoder, maxInputLen would be reset in trtEncoderModel to maxInputLen: min(maxSequenceLen, maxNumTokens).
> [TensorRT-LLM][INFO] Capacity Scheduler Policy: GUARANTEED_NO_EVICT
> [TensorRT-LLM][INFO] Context Chunking Scheduler Policy: None
> [TensorRT-LLM][INFO] Loaded engine size: 5313 MiB
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 1000.77 MiB for execution context memory.
> [TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 5305 (MiB)
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 340.55 MB GPU memory for runtime buffers.
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 886.55 MB GPU memory for decoder.
> [TensorRT-LLM][INFO] Memory usage when calculating max tokens in paged kv cache: total: 22.19 GiB, available: 14.57 GiB
> [TensorRT-LLM][INFO] Number of blocks in KV cache primary pool: 3836
> [TensorRT-LLM][INFO] Number of blocks in KV cache secondary pool: 0, onboard blocks to primary memory before reuse: true
> [TensorRT-LLM][INFO] Max KV cache pages per sequence: 512
> [TensorRT-LLM][INFO] Number of tokens per block: 64.
> [TensorRT-LLM][INFO] [MemUsageChange] Allocated 13.11 GiB for max tokens in paged KV cache (245504).
> [09/02/2024-13:17:36] [TRT-LLM] [I] Load engine takes: 2.850294351577759 sec
> Input [Text 0]: "<|im_start|>system
> You are a helpful assistant.<|im_end|>
> <|im_start|>user
> 马儿几条腿<|im_end|>
> <|im_start|>assistant
> "
> Output [Text 0 Beam 0]: "马有四条腿。"
> [TensorRT-LLM][INFO] Refreshed the MPI local session
> ```
> 
> The package list is as follows:
> 
> ```
> Package                  Version
> ------------------------ -----------
> accelerate               0.33.0
> aenum                    3.1.15
> aiohappyeyeballs         2.4.0
> aiohttp                  3.10.5
> aiosignal                1.3.1
> annotated-types          0.7.0
> anyio                    4.4.0
> async-timeout            4.0.3
> attrs                    24.2.0
> auto_gptq                0.7.1
> build                    1.2.1
> certifi                  2024.8.30
> charset-normalizer       3.3.2
> click                    8.1.7
> click-option-group       0.5.6
> cloudpickle              3.0.0
> colored                  2.2.4
> coloredlogs              15.0.1
> cuda-python              12.6.0
> datasets                 2.21.0
> diffusers                0.30.2
> dill                     0.3.8
> distro                   1.9.0
> evaluate                 0.4.2
> exceptiongroup           1.2.2
> filelock                 3.15.4
> frozenlist               1.4.1
> fsspec                   2024.6.1
> gekko                    1.2.1
> h11                      0.14.0
> h5py                     3.10.0
> httpcore                 1.0.5
> httpx                    0.27.2
> huggingface-hub          0.24.6
> humanfriendly            10.0
> idna                     3.8
> importlib_metadata       8.4.0
> janus                    1.0.0
> Jinja2                   3.1.4
> jiter                    0.5.0
> lark                     1.2.2
> markdown-it-py           3.0.0
> MarkupSafe               2.1.5
> mdurl                    0.1.2
> mpi4py                   4.0.0
> mpmath                   1.3.0
> multidict                6.0.5
> multiprocess             0.70.16
> networkx                 3.3
> ninja                    1.11.1.1
> numpy                    1.26.4
> nvidia-cublas-cu12       12.1.3.1
> nvidia-cuda-cupti-cu12   12.1.105
> nvidia-cuda-nvrtc-cu12   12.1.105
> nvidia-cuda-runtime-cu12 12.1.105
> nvidia-cudnn-cu12        9.1.0.70
> nvidia-cufft-cu12        11.0.2.54
> nvidia-curand-cu12       10.3.2.106
> nvidia-cusolver-cu12     11.4.5.107
> nvidia-cusparse-cu12     12.1.0.106
> nvidia-modelopt          0.15.1
> nvidia-nccl-cu12         2.20.5
> nvidia-nvjitlink-cu12    12.6.68
> nvidia-nvtx-cu12         12.1.105
> onnx                     1.16.2
> openai                   1.43.0
> optimum                  1.21.4
> packaging                24.1
> pandas                   2.2.2
> peft                     0.12.0
> pillow                   10.3.0
> pip                      24.2
> polygraphy               0.49.9
> protobuf                 5.28.0
> psutil                   6.0.0
> PuLP                     2.9.0
> pyarrow                  17.0.0
> pydantic                 2.8.2
> pydantic_core            2.20.1
> Pygments                 2.18.0
> pynvml                   11.5.3
> pyproject_hooks          1.1.0
> python-dateutil          2.9.0.post0
> pytz                     2024.1
> PyYAML                   6.0.2
> regex                    2024.7.24
> requests                 2.32.3
> rich                     13.8.0
> rouge                    1.0.1
> safetensors              0.4.4
> scipy                    1.14.1
> sentencepiece            0.2.0
> setuptools               72.1.0
> six                      1.16.0
> sniffio                  1.3.1
> StrEnum                  0.4.15
> sympy                    1.13.2
> tensorrt                 10.3.0
> tensorrt-cu12            10.3.0
> tensorrt-cu12-bindings   10.3.0
> tensorrt-cu12-libs       10.3.0
> tensorrt-llm             0.12.0
> tokenizers               0.19.1
> tomli                    2.0.1
> torch                    2.4.0
> tqdm                     4.66.5
> transformers             4.42.4
> triton                   3.0.0
> typing_extensions        4.12.2
> tzdata                   2024.1
> urllib3                  2.2.2
> wheel                    0.43.0
> xxhash                   3.5.0
> yarl                     1.9.7
> zipp                     3.20.1
> ```
> 
> fresh python3.10 conda env with tensorrt-llm installed with pip and extra nvidia package index

think you!  I use A100, I will try to run by your environment.

**Comment by exceedzhang** [comment]
推理出现乱码
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/28929bff-ca95-409d-8184-e66950a71f5e">

**Comment by ljy805** [comment]
> 推理出现乱码 <img alt="image" width="1026" src="https://private-user-images.githubusercontent.com/4583537/369618571-28929bff-ca95-409d-8184-e66950a71f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDU2MTYsIm5iZiI6MTcyNzI0NTMxNiwicGF0aCI6Ii80NTgzNTM3LzM2OTYxODU3MS0yODkyOWJmZi1jYTk1LTQwOWQtODE4NC1lNjY5NTBhNzFmNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMDYyMTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRkNTVjMTZhNmVmNzBlY2QyZmRhNzFjOTZkODcwZDk2NTZjYWUyMjc3ODA5ZDFlMDA0MDk3YjlkMjEwZDJkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.guoLy0u2c3_lGErP1IZCyjbIK0MPkF40l3UR8yKen0M"
请问有解决么？
