### ISSUE TITLE
流式情况下 function call的问题。

### ISSUE THREAD

**Issue by monkeywl2020** [QwenLM/Qwen2.5#902]
测试中发现，在携带function call的tools信息的时候，llm会根据用户的提示词决定是否调用function call。

在流式输出的情况下有个问题，就是有时候 Qwen2 llm会返回 2条消息，第一条是普通用户的答复，类似claude哪有的思考内容。第二条才是 function call的内容。

流式响应的时候，如果携带了function call的内容的话，在流式输出的情况下，除了内容全部输出完整后才能判断是否有 function call。这样会导致无法判断当前消息是普通用户消息还是携带了function call的消息。claude如果有function call的思维过程的时候会在返回的消息中携带stop_reason 里面的结果是 tool_use，根据这个内容可以判断当前是否会调用function call。

一般情况下，给用户的消息流式可以流式输出给用户。function call的消息不用给用户，收完再执行function 调用后再根据情况输出。

请考虑下这个问题怎么解决？

**Comment by JianxinMa** [comment]
我其实没有太理解当前的设计为什么会有影响。

收到一条消息 message 后，看下 message.content 是否有内容，有则放心流式输出 message.content 给用户即可（即使message带有function_call信息也可以放心输出message.content）。

如果一条message的function_call有值，则只需要等到模型推理完毕、或者获得了“下一条message”时，再开始处理当前message的function_call。

**Comment by monkeywl2020** [comment]
流式的qwen2.5支持了 openAI格式的，也是一样的，只能采用用户注册回调的方式进行流式处理，否则会比较复杂。暂时先这样了。

**Comment by RayneSun** [comment]
你好，我也有这样的问题，其实就是有tool_calls时，我们不希望把思考内容暴露给用户，而是隐式的处理这条消息并调用工具。因此我们希望在流式开始的时候就能分辨content里面的内容是否是工具调用的思考还是返回给用户的message。然而<tool_calls>是在content后面的
