### ISSUE TITLE
[Badcase]: Fine tuning  Qwen2-72b-Instruct using QLoRA with bnb, model indicators  grad_norm=Nan; loss=0

### ISSUE THREAD

**Issue by Jackmoyu001** [QwenLM/Qwen2.5#912]
### Model Series

Qwen2

### What are the models used?

 Qwen2-72B-Instruct

### What is the scenario where the problem happened?

微调模型时，模型指标异常。使用了transformers、peft,

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

操作系统： Ubuntu 22.04
Python：Python 3.10
GPU：7 个 NVIDIA 3090 24G
NVIDIA 驱动程序：535
CUDA 编译器：12.2
PyTorch：2.1.2+cu121

#### Steps to reproduce

This happens to Qwen2-72B-Instruct .
The badcase can be reproduced with the following steps:
1. My code and parameters are as follows
<img width="776" alt="9d5007b65e424a5f328beecb36736f0" src="https://github.com/user-attachments/assets/323503bc-e37b-4df7-9648-d9bd2807bfaa">
The executed instruction is python xxx. py

####The problem that has arisen is
<img width="354" alt="error" src="https://github.com/user-attachments/assets/fb7e2c17-f899-4058-9458-62e158ec7d02">
<img width="735" alt="fa84c668059383242813f712535dd16" src="https://github.com/user-attachments/assets/eb5e063f-5629-4ae7-9fdd-ea0ddbe1b8a6">

#### Attempts to fix

I have tried several ways to fix this, including:
1. adjusting the sampling parameters, but not resolved

**Comment by errfgod** [comment]
same issue with qwen2.5_7B_instruct

**Comment by jklj077** [comment]
could you try removing use_double_quant? there are also data-free quantization methods other than BnB that QLoRA could use in transformers/peft, e.g., HQQ or EETQ. please refer to <https://huggingface.co/docs/peft/v0.13.0/developer_guides/quantization>. in addition, you can load a quantized model (AWQ or GPTQ).
