### ISSUE TITLE
[Question]: vllm本地部署如何使用tools

### ISSUE THREAD

**Issue by lullabies777** [QwenLM/Qwen2.5#915]
### Has this been raised before?

- [X] I have checked [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.
- [X] I confirm that this is not a bug report, a feature request, or a badcase.

### Description

目前vllm部署使用tools要开enable-auto-tool-choice，但是tool-call-parser只支持`hermes` or `mistral`，简介说vllm支持tools，请问一下如何用vllm本地部署支持tools,是要自己写parser嘛
![image](https://github.com/user-attachments/assets/19082279-8735-444a-b7c0-af16143f3fa3)

**Comment by jklj077** [comment]
Hi, please refer to [our blog](https://qwenlm.github.io/zh/blog/qwen2.5/) (search for tool calling) or [documentation](https://qwen.readthedocs.io/zh-cn/latest/framework/function_call.html#vllm) for tool use with Qwen2.5.

![image](https://github.com/user-attachments/assets/7de2c6aa-b187-4b27-8a6b-ca6f236983b6)
Please do check the Qwen documentation.

**Comment by lullabies777** [comment]
> Hi, please refer to [our blog](https://qwenlm.github.io/zh/blog/qwen2.5/) (search for tool calling) or [documentation](https://qwen.readthedocs.io/zh-cn/latest/framework/function_call.html#vllm) for tool use with Qwen2.5.
> 
> ![image](https://private-user-images.githubusercontent.com/17811943/368831131-7de2c6aa-b187-4b27-8a6b-ca6f236983b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTcxOTYsIm5iZiI6MTcyNjcxNjg5NiwicGF0aCI6Ii8xNzgxMTk0My8zNjg4MzExMzEtN2RlMmM2YWEtYjE4Ny00YjI3LThhNmItY2E2ZjIzNjk4M2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAzMzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWY4ODliYzdlN2YxZjU4MDFmZWUzNjEzNGQ1YzIwNWVkNGUxNjhjODljMTMxZTcyN2RmNThiOWE1NjI1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iv1VFQzxOc-ed7w66_gOe6dhHjqCpFt7mN46Fm9IhCo) Please do check the Qwen documentation.

Thanks for reply! My bad!

**Comment by lonngxiang** [comment]
使用报错：

ERROR 09-19 01:43:30 hermes_tool_parser.py:103] Error in extracting tool call from response Expecting property name enclosed in double quotes: line 2 column 2 (char 2)

**Comment by lonngxiang** [comment]
> > Hi, please refer to [our blog](https://qwenlm.github.io/zh/blog/qwen2.5/) (search for tool calling) or [documentation](https://qwen.readthedocs.io/zh-cn/latest/framework/function_call.html#vllm) for tool use with Qwen2.5.
> > ![image](https://private-user-images.githubusercontent.com/17811943/368831131-7de2c6aa-b187-4b27-8a6b-ca6f236983b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTcxOTYsIm5iZiI6MTcyNjcxNjg5NiwicGF0aCI6Ii8xNzgxMTk0My8zNjg4MzExMzEtN2RlMmM2YWEtYjE4Ny00YjI3LThhNmItY2E2ZjIzNjk4M2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAzMzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWY4ODliYzdlN2YxZjU4MDFmZWUzNjEzNGQ1YzIwNWVkNGUxNjhjODljMTMxZTcyN2RmNThiOWE1NjI1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iv1VFQzxOc-ed7w66_gOe6dhHjqCpFt7mN46Fm9IhCo) Please do check the Qwen documentation.
> 
> Thanks for reply! My bad!

你这能正常运行吗

**Comment by lullabies777** [comment]
> > > Hi, please refer to [our blog](https://qwenlm.github.io/zh/blog/qwen2.5/) (search for tool calling) or [documentation](https://qwen.readthedocs.io/zh-cn/latest/framework/function_call.html#vllm) for tool use with Qwen2.5.
> > > ![image](https://private-user-images.githubusercontent.com/17811943/368831131-7de2c6aa-b187-4b27-8a6b-ca6f236983b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTcxOTYsIm5iZiI6MTcyNjcxNjg5NiwicGF0aCI6Ii8xNzgxMTk0My8zNjg4MzExMzEtN2RlMmM2YWEtYjE4Ny00YjI3LThhNmItY2E2ZjIzNjk4M2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAzMzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWY4ODliYzdlN2YxZjU4MDFmZWUzNjEzNGQ1YzIwNWVkNGUxNjhjODljMTMxZTcyN2RmNThiOWE1NjI1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iv1VFQzxOc-ed7w66_gOe6dhHjqCpFt7mN46Fm9IhCo) Please do check the Qwen documentation.
> > 
> > 
> > Thanks for reply! My bad!
> 
> 你这能正常运行吗

可以运行，但是出现了和最新那个帖子一样的问题，function call是在content里面，tool_calls是空的

**Comment by jklj077** [comment]
Hi, should be fixed now, please pull the model files again (updating the tokenizer_config.json is enough).

**Comment by kingxjs** [comment]
> 嗨，现在应该修复了，请再次拉取模型文件（更新tokenizer_config.json就足够了）。如果问题仍然存在，请随时重新打开。

May I ask if the ollama mirror has been updated, found that using [14b](https://ollama.com/library/qwen2.5:14b) 7cdf5a0187d5, tool_calls is still empty

**Comment by mawenju203** [comment]
> Hi, should be fixed now, please pull the model files again (updating the tokenizer_config.json is enough). Feel free to reopen if the problem persists.

你好，我这边Qwen2.5-7B-Instruct-AWQ；也出现了；代码和模型都是这周（2024年9月24号）下载的；使用是vllm=0.6.1.post2版本；

使用vllm启动的：vllm serve Qwen/Qwen2.5-7B-Instruct --enable-auto-tool-choice --tool-call-parser hermes

结果生成：

![image](https://github.com/user-attachments/assets/b9dc0ebc-9739-4e7a-9e77-7f30c29be6cb)

**Comment by a-gull** [comment]
> > Hi, should be fixed now, please pull the model files again (updating the tokenizer_config.json is enough). Feel free to reopen if the problem persists.
> 
> 你好，我这边Qwen2.5-7B-Instruct-AWQ；也出现了；代码和模型都是这周（2024年9月24号）下载的；使用是vllm=0.6.1.post2版本；
> 
> 使用vllm启动的：vllm serve Qwen/Qwen2.5-7B-Instruct --enable-auto-tool-choice --tool-call-parser hermes
> 
> 结果生成：
> 
> ![image](https://private-user-images.githubusercontent.com/30227934/370632504-b9dc0ebc-9739-4e7a-9e77-7f30c29be6cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTMwMzEsIm5iZiI6MTczNDU5MjczMSwicGF0aCI6Ii8zMDIyNzkzNC8zNzA2MzI1MDQtYjlkYzBlYmMtOTczOS00ZTdhLTllNzctN2YzMGMyOWJlNmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA3MTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OWYyOWE3NGQ1MDI0NzVjZTFmZmRkMDExMTA1OTk1ZTk3ODg0MDRkNmIyOTEwYWRiOGRiNDUxNGI1ZDhmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KeBCfNj3ClBIbOl5QJfITcO5hqiA0aKBqefHHfIn_6A)

请问你这个问题现在解决了吗？
