### ISSUE TITLE
[Question]: qwen2.5 agent使用问题

### ISSUE THREAD

**Issue by lonngxiang** [QwenLM/Qwen2.5#918]
### Has this been raised before?

- [X] I have checked [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.
- [X] I confirm that this is not a bug report, a feature request, or a badcase.

### Description

运行报错：
```

response = client.chat.completions.create(
    model="/ai/qwen2.5/",
    messages=[{"role": "user", "content": "1+1="}],

    tools=tools,
    temperature=0.7,
    top_p=0.8,
    max_tokens=512,
    extra_body={
        "repetition_penalty": 1.05,
    },
```
Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='<tool_call>\n{{"name": "add_numbers", "arguments": {"a": 1, "b": 1}}}\n</tool_call>', role='assistant', function_call=None, tool_calls=[]), stop_reason=None)

![image](https://github.com/user-attachments/assets/98e921ba-15ab-4dc5-94f5-09d57ee3b57c)

**Comment by jklj077** [comment]
what is this? is it vllm? how did you start it?

**Comment by lonngxiang** [comment]
> what is this? is it vllm? what version? how did you start it?

vllm 0.6.1.post2
```
CUDA_VISIBLE_DEVICES=1 vllm serve  /ai/qwen2.5/ --host 192.16*** --port 10868 --max-model-len 2000 --trust-remote-code --api-key token-abc123 --gpu_memory_utilization 1 --trust-remote-code  --disable-frontend-multiprocessing --tensor-parallel-size 1  --enable-auto-tool-choice --tool-call-parser hermes
```

**Comment by jklj077** [comment]
Hi, we have identified an issue with the released chat template, which we will fix soon. 

For now please try the following template:
```jinja
{%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0]['role'] == 'system' %}
        {{- messages[0]['content'] }}
    {%- else %}
        {{- 'You are Qwen, created by Alibaba Cloud. You are a helpful assistant.' }}
    {%- endif %}
    {{- "\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0]['role'] == 'system' %}
        {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}
    {%- else %}
        {{- '<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) or (message.role == "assistant" and not message.tool_calls) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {{- '<|im_start|>' + message.role }}
        {%- if message.content %}
            {{- '\n' + message.content }}
        {%- endif %}
        {%- for tool_call in message.tool_calls %}
            {%- if tool_call.function is defined %}
                {%- set tool_call = tool_call.function %}
            {%- endif %}
            {{- '\n<tool_call>\n{"name": "' }}
            {{- tool_call.name }}
            {{- '", "arguments": ' }}
            {{- tool_call.arguments | tojson }}
            {{- '}\n</tool_call>' }}
        {%- endfor %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if (loop.index0 == 0) or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
{%- endif %}
```

You can save it to, say, `template.jinja` and apply it as 
```
vllm ... --enable-auto-tool-choice --tool-call-parser hermes --chat-template template.jinja 
```

**Comment by lonngxiang** [comment]
> --chat-template template.jinja

Okay, looking forward to the repair soon.

**Comment by jklj077** [comment]
Hi, should be fixed now, please pull the model files again (updating the tokenizer_config.json is enough). Feel free to reopen if the problem persists.

**Comment by mawenju203** [comment]
@jklj077 
vllm版本0.6.1.post2
transformers版本：4.44.2
qwen-agent版本：0.0.10

启动的服务是：vllm serve Qwen/Qwen2.5-7B-Instruct --enable-auto-tool-choice --tool-call-parser hermes
`{
    "messages": [
        {
            "content": "Follow a pattern of THOUGHT (reason step-by-step about which function to call next), ACTION (call a function to as a next step towards the final answer), OBSERVATION (output of the function). Reason step by step which actions to take to get to the answer. Only call functions with arguments coming verbatim from the user or the output of other functions.",
            "role": "system"
        },
        {
            "content": "你好呀",
            "role": "user"
        },
        {
            "content": "- Likes Chinese greetings\n- Prefers to engage in conversation\n- Prefers to help with questions\n- Speaks Chinese",
            "role": "assistant"
        },
        {
            "content": "你好呢",
            "role": "user"
        }
    ],
    "model": "./Qwen2.5-7B-Instruct-AWQ",
    "stream": false,
    "temperature": 0.0,
    "tools": [
        {
            "function": {
                "description": "闲聊工具,仅用于跟用户问好。",
                "name": "FeeyoLLM",
                "parameters": {
                    "properties": {
                        "question": {
                            "description": "用户的问题",
                            "type": "string"
                        }
                    },
                    "required": [
                        "question"
                    ],
                    "type": "object"
                }
            },
            "type": "function"
        }
    ],
    "top_p": 1.0
}`

模型返回的结果：

![image](https://github.com/user-attachments/assets/6b9b74ef-7087-4390-aa53-d4ad66027a3e)

**Comment by JianxinMa** [comment]
> {
>             "content": "Follow a pattern of THOUGHT (reason step-by-step about which function to call next), ACTION (call a function to as a next step towards the final answer), OBSERVATION (output of the function). Reason step by step which actions to take to get to the answer. Only call functions with arguments coming verbatim from the user or the output of other functions.",
>             "role": "system"
>         },

您好，我注意到您这个例子里指定了system：
```
        {
            "content": "Follow a pattern of THOUGHT (reason step-by-step about which function to call next), ACTION (call a function to as a next step towards the final answer), OBSERVATION (output of the function). Reason step by step which actions to take to get to the answer. Only call functions with arguments coming verbatim from the user or the output of other functions.",
            "role": "system"
        },
```
在使用vllm的tool call功能时，不建议您额外配置这类和工具调用相关的system。建议去掉该system message再试试。

**Comment by mawenju203** [comment]
> > {
> > "content": "Follow a pattern of THOUGHT (reason step-by-step about which function to call next), ACTION (call a function to as a next step towards the final answer), OBSERVATION (output of the function). Reason step by step which actions to take to get to the answer. Only call functions with arguments coming verbatim from the user or the output of other functions.",
> > "role": "system"
> > },
> 
> 您好，我注意到您这个例子里指定了system：
> 
> ```
>         {
>             "content": "Follow a pattern of THOUGHT (reason step-by-step about which function to call next), ACTION (call a function to as a next step towards the final answer), OBSERVATION (output of the function). Reason step by step which actions to take to get to the answer. Only call functions with arguments coming verbatim from the user or the output of other functions.",
>             "role": "system"
>         },
> ```
> 
> 在使用vllm的tool call功能时，不建议您额外配置这类和工具调用相关的system。建议去掉该system message再试试。

好的，谢谢您的回复
