### ISSUE TITLE
[Badcase]: repetition after the conversation and send endless emoji (Ollama + OpenwebUI)

### ISSUE THREAD

**Issue by valleysprings** [QwenLM/Qwen2.5#920]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-72B

### What is the scenario where the problem happened?

Qwen2.5-72B gets repetitive and send endless emoji after the useful conversation ends

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

OS: Ubuntu 22.04
Python: Python 3.12
GPUs: 2 x NVIDIA A100
NVIDIA driver: 560
CUDA compiler: 12.6
Ollama 0.3.11

#### Steps to reproduce

This happens to Qwen2.5-72B
The badcase can be reproduced with the following steps:
1. no system prompt
2. default hyperparameter

The following example input & output can be used:
1. 条件熵 相对熵 互信息 kl 散度 定义 和 联系
2. 怎么证明互信息是从条件熵推过来的 计算一下

#### Expected results

The results are expected to be no repetition and end the conversation.

#### Anything else helpful for investigation

I find that this problem also happens to ... 
<img width="1541" alt="image" src="https://github.com/user-attachments/assets/7814bc28-cdc4-4e28-99fb-70210775cfcb">

**Comment by CRCODE22** [comment]
This model is insane in a negative way when used in OpenWebui it is hallucinating and talking to itself I tried the 32B version. Creepy thing keeps going on about a daughter. Worst model so far I have tested in OpenWebui and I have tested many.

**Comment by DoiiarX** [comment]
千问商业版本也有这个bug，而且稳定复现。

**Comment by jklj077** [comment]
@DoiiarX it's an issue about ollama and openwebui. yours are totally different. if you are using comercial service, open a ticket.
