### ISSUE TITLE
[Badcase]: Loss does not drop when using Liger Kernel at Qwen2.5

### ISSUE THREAD

**Issue by Se-Hun** [QwenLM/Qwen2.5#921]
### Has this been raised before?

- [X] I have checked [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.
- [X] I confirm that this is not a bug report, a feature request, or a badcase.

### Description

Hello, 

### In my case:
I am trying to instruction tuning Qwen2.5-14B-Instruct with [Liger Kernel](https://github.com/linkedin/Liger-Kernel).

### There is my question:
I know that the liger kernel is supported in the dev version of huggingface transformers. However, when training the Qwen2.5 model with Liger Kernel, the loss value does not drop. Not supported yet at Qwen2.5?

**Comment by jklj077** [comment]
Hi, unfortunately, I don't think we have any experience with it. Would mind reporting this to the Liger Kernel maintainers?

**Comment by jklj077** [comment]
Hi, could you please provide more info on this? did you use frameworks like axolotl, llama-factory, or others? which type of chat templates and which script did you run? transformers have released a version that support Liger Kernel, could you give it a try?
