### ISSUE TITLE
[Badcase]: 用vllm0.6.0版本部署qwen2.5-14B后，推理结果为prompt

### ISSUE THREAD

**Issue by Jayc-Z** [QwenLM/Qwen2.5#922]
### Model Series

Qwen2.5

### What are the models used?

qwen2.5-14B

### What is the scenario where the problem happened?

qwen2.5-14B fail to inference 

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

![image](https://github.com/user-attachments/assets/e3cd688a-5240-42a4-97fb-5bd9535641ab)
推理结果为prompt重复

#### Steps to reproduce

This happens to Qwen2.5-xB-Instruct-xxx and xxx.
The badcase can be reproduced with the following steps:
1. ...
2. ...

The following example input & output can be used:
```
system: ...
user: ...
...
```

#### Expected results

The results are expected to be ...

#### Attempts to fix

I have tried several ways to fix this, including:
1. adjusting the sampling parameters, but ...
2. prompt engineering, but ...

#### Anything else helpful for investigation

I find that this problem also happens to ...

**Comment by jklj077** [comment]
Hi, please provide step to reproduce, including how you inference with vllm. In addition, I wonder why you were using Qwen2.5-14B instead of Qwen2.5-14-Instruct?

**Comment by Jayc-Z** [comment]
Hi,thanks for your reply.I want to compare Qwen2.5-14B and Qwen2.5-14-Instruct, and the latter inferenced successfully .
My vllm script is as follows, the version is 0.6.0:
![image](https://github.com/user-attachments/assets/c00fc301-e33a-4a2b-aee4-1417a58d30ac)
My Call script is as follows:
![image](https://github.com/user-attachments/assets/b6725a96-caba-45cf-8150-a715201c3a31)

**Comment by jklj077** [comment]
I see. The problem is that, as stated in [the model card](https://huggingface.co/Qwen/Qwen2.5-14B), the base models, in your case Qwen2.5-14B, are not supposed to be directly used for chat. 

![image](https://github.com/user-attachments/assets/b19b80ac-d2f0-4de1-9bd1-b1110b3aefaa)


For differences between base and instruct models, you can also see [our documentation](https://qwen.readthedocs.io/zh-cn/latest/getting_started/concepts.html#causal-language-models).
In addition, the sampling parameter `temperature=0.1` is also small for a base model, if used for completion instead of chat completion. You can see [here](https://qwen.readthedocs.io/zh-cn/latest/deployment/vllm.html#openai-compatible-api-service) for our recommended sampling parameters.

**Comment by Jayc-Z** [comment]
> I see. The problem is that, as stated in [the model card](https://huggingface.co/Qwen/Qwen2.5-14B), the base models, in your case Qwen2.5-14B, are not supposed to be directly used for chat.
> 
> ![image](https://private-user-images.githubusercontent.com/17811943/368924677-b19b80ac-d2f0-4de1-9bd1-b1110b3aefaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzgzMjgsIm5iZiI6MTcyNjczODAyOCwicGF0aCI6Ii8xNzgxMTk0My8zNjg5MjQ2NzctYjE5YjgwYWMtZDJmMC00ZGUxLTliZDEtYjExMTBiM2FlZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA5MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNDdlNTg1YTkyMjc0NmQwNTI2YzM4OGMyNzVlZmE3ZDQ3NTBiNTM1NWQzZDk5YzkyMGE1YjlmOThlNDM2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qAVKQwJrwww_eAOZMd3K1hu8-6C0lP-0EBYTt_JiU_o)
> 
> For differences between base and instruct models, you can also see [our documentation](https://qwen.readthedocs.io/zh-cn/latest/getting_started/concepts.html#causal-language-models). In addition, the sampling parameter `temperature=0.1` is also small for a base model, if used for completion instead of chat completion. You can see [here](https://qwen.readthedocs.io/zh-cn/latest/deployment/vllm.html#openai-compatible-api-service) for our recommended sampling parameters.

Thanks for your response!
