### ISSUE TITLE
[Question]: 请问Qwen2.5推理似乎有一些异常

### ISSUE THREAD

**Issue by zhangch-ss** [QwenLM/Qwen2.5#926]
### Has this been raised before?

- [X] I have checked [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.
- [X] I confirm that this is not a bug report, a feature request, or a badcase.

### Description

请问调试中出现Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.是什么原因呢？
![image](https://github.com/user-attachments/assets/0d85d97a-cef9-4862-8d01-b650299b81f6)

**Comment by Yiir-1** [comment]
我也遇到这个问题了 请问怎么解决的呢？
