### ISSUE TITLE
[Badcase]: 相同的数据，微调时在qwen2.5 72B预训练模型上的loss是qwen2 72B的3倍，请问2.5除了数据变多了，其他有什么不一样吗

### ISSUE THREAD

**Issue by boundles** [QwenLM/Qwen2.5#935]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-72B预训练模型

### What is the scenario where the problem happened?

text to sql

### Is this badcase known and can it be solved using avaiable techniques?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find a solution there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

OS: Ubuntu 22.04
Python: Python 3.11
GPUs: 8 x NVIDIA A100

### Description

如标题所描述

**Comment by cipolee** [comment]
mark，用lora微调7b instruction模型时也相比qwen2的loss高一些

**Comment by airstillblue** [comment]
遇到类似问题，同样的环境，loss高一大截。

**Comment by Songjw133** [comment]
可以查查是不是eos_token的问题？看一下微调数据添加的序列最后的结束符是什么？
我微调qwen2.5基础模型，用的自己写的微调代码。昨天一开始试的时候，loss也很高，检查了一下tokenizer的eos_token添加的是<|im_end|>，正常来说应该是<|endoftext|>（这个问题今天已经修复了），把eos_token换成<|endoftext|>，loss就正常了。

**Comment by boundles** [comment]
> 可以查查是不是eos_token的问题？检查一下添加到输入序列最后的结束符是什么。 我微调qwen2.5基础模型，用的自己写的微调代码。昨天一开始试的时候，loss也很高，检查了一下tokenizer的eos_token添加的是<|im_end|>，正常来说应该是<|endoftext|>（这个问题今天已经修复了），把eos_token换成<|endoftext|>，loss就正常了。

是说结束符是<|endoftext|>，而不是<|im_end|>?

**Comment by Songjw133** [comment]
> > 可以查查是不是eos_token的问题？检查一下添加到输入序列最后的结束符是什么。 我微调qwen2.5基础模型，用的自己写的微调代码。昨天一开始试的时候，loss也很高，检查了一下tokenizer的eos_token添加的是<|im_end|>，正常来说应该是<|endoftext|>（这个问题今天已经修复了），把eos_token换成<|endoftext|>，loss就正常了。
> 
> 是说结束符是<|endoftext|>，而不是<|im_end|>?

对的base模型的结束符是<|endoftext|>，对应token id是151643。你可以看看输入数据的结束符，如果是<|im_end|>（id是151645）或者用了聊天模板加上了<|im_end|>，那可能就是这个问题。

**Comment by boundles** [comment]
> > > 可以查查是不是eos_token的问题？检查一下添加到输入序列最后的结束符是什么。 我微调qwen2.5基础模型，用的自己写的微调代码。昨天一开始试的时候，loss也很高，检查了一下tokenizer的eos_token添加的是<|im_end|>，正常来说应该是<|endoftext|>（这个问题今天已经修复了），把eos_token换成<|endoftext|>，loss就正常了。
> > 
> > 
> > 是说结束符是<|endoftext|>，而不是<|im_end|>?
> 
> 对的base模型的结束符是<|endoftext|>，对应token id是151643。你可以看看输入数据的结束符，如果是<|im_end|>（id是151645），那可能就是这个问题。 也注意一下是不是用了聊天模板。base模型微调不应该带模板的。聊天模板会自动加上<|im_end|>，也会导致loss很高。我也不知道啥情况，qwen2其实无所谓这些的，但qwen2.5换一个eos_token loss差异就很大。

把结束符换成了endoftext，loss更高了，感觉不像是这个问题

**Comment by white-wolf-tech** [comment]
我本地微调也遇到同样问题。
使用Qwen1.5-4B微调模型，loss、梯度正常下降
使用Qwen2.5-3B，loss降不下去

**Comment by white-wolf-tech** [comment]
基座模型，我使用了<|im_start|> text <|im_end|>这样的格式。发现是不能收敛的。

更换成text<|endoftext|>，这样训练就正常了

**Comment by 520jefferson** [comment]
> 可以查查是不是eos_token的问题？检查一下添加到输入序列最后的结束符是什么。 我微调qwen2.5基础模型，用的自己写的微调代码。昨天一开始试的时候，loss也很高，检查了一下tokenizer的eos_token添加的是<|im_end|>，正常来说应该是<|endoftext|>（这个问题今天已经修复了），把eos_token换成<|endoftext|>，loss就正常了。

你微调的标志符号，跟预训练是不一样的，你怎么区分system， user，bot呢？为何不基于instruct微调呢？

**Comment by jklj077** [comment]
Hi, guys! I wonder how did you actually finetune the base model. Is it full parameter finetuning, or LoRA, or other methods?

**Comment by Songjw133** [comment]
> > 可以查查是不是eos_token的问题？检查一下添加到输入序列最后的结束符是什么。 我微调qwen2.5基础模型，用的自己写的微调代码。昨天一开始试的时候，loss也很高，检查了一下tokenizer的eos_token添加的是<|im_end|>，正常来说应该是<|endoftext|>（这个问题今天已经修复了），把eos_token换成<|endoftext|>，loss就正常了。
> 
> 你微调的标志符号，跟预训练是不一样的，你怎么区分system， user，bot呢？为何不基于instruct微调呢？

我微调的是类似文本分类的那种NLU任务，不需要对话，system， user这些特殊token都不需要。只在最后加了个eos用于推理时结束生成。
用base模型是因为我感觉base模型的任务指标比instruct好一点点。

**Comment by Songjw133** [comment]
> Hi, guys! I wonder how did you actually finetune the base model. Is it full parameter finetuning, or LoRA, or other methods? What's the prompt format you have used?

我是用的LoRA微调。我感觉就是eos或其他特殊token的问题。

**Comment by jklj077** [comment]
If you use LoRA on the base models, you need to finetune the embeddings and the lm_head if you use the ChatML template.

**Comment by white-wolf-tech** [comment]
> If you use LoRA on the base models, you need to finetune the embeddings and the lm_head if you use the ChatML template.
使用ChatML方式。
Qwen2.5-3B，是使用共享embedding的方式。lora的 modules_to_save=["embed_tokens"]，还是不能收敛。
modules_to_save=["embed_tokens", "lm_head"]是可以收敛的，但是3B里面就没有lm_head这一层呀。

请问这种是什么问题导致的？Qwen1.5-4B里面，没有这个问题  @jklj077

**Comment by white-wolf-tech** [comment]
> > If you use LoRA on the base models, you need to finetune the embeddings and the lm_head if you use the ChatML template.
> > 使用ChatML方式。
> > Qwen2.5-3B，是使用共享embedding的方式。lora的 modules_to_save=["embed_tokens"]，还是不能收敛。
> > modules_to_save=["embed_tokens", "lm_head"]是可以收敛的，但是3B里面就没有lm_head这一层呀。
> 
> 请问这种是什么问题导致的？Qwen1.5-4B里面，没有这个问题 @jklj077

参考了DataCollatorForChatML ，目前正常

**Comment by jklj077** [comment]
> Qwen2.5-3B，是使用共享embedding的方式。lora的 modules_to_save=["embed_tokens"]，还是不能收敛。
modules_to_save=["embed_tokens", "lm_head"]是可以收敛的，但是3B里面就没有lm_head这一层呀。

lm_head exists but its parameter is shared with embed_tokens.

> Qwen1.5-4B里面，没有这个问题

For 4B, the embed_tokens and the lm_head are untied.
