### ISSUE TITLE
[Bug]: When I use Qwen2.5-7B-Instruct-GPTQ-Int4/Int8, some error occurs

### ISSUE THREAD

**Issue by volcano1995** [QwenLM/Qwen2.5#951]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-7B-Instruct-GPTQ

### What is the scenario where the problem happened?

inference

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

CUDA 11.8  pytorch 2.0.1

### Log output

```shell
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

### Description

When I use Qwen2.5-7B-Instruct-GPTQ-Int4/Int8, some error occurs as follows

CUDA 11.8 pytorch 2.0.1 
![Uploading image.png…]()

**Comment by huashiyiqike** [comment]
same here
https://github.com/QwenLM/Qwen2.5/issues/930#issuecomment-2370022840

**Comment by Ryan-0805** [comment]
A100 8卡使用transformers运行Qwen2.5-72B-Instruct-GPTQ同样存在这个问题，但是用VLLM没有问题，请问下是什么原因

**Comment by jklj077** [comment]
@Ryan-0805 Thank you for describing what you were using. In that case, please use vLLM; the exllama v2 CUDA kernel in auto_gptq uses fp16 for matmul accumulate which could be numerically instable depending on the usecase.

**Comment by PIPItian** [comment]
原因是Qwen2.5的o以及MLP的线性层中不再有bias参数，遇到此warning时要将transformer的optimum库更新到最新版，不然在构造模型时会读取到错误的Bias参数，导致后续计算出错

**Comment by jklj077** [comment]
That's not the case. @PIPItian

**Comment by PIPItian** [comment]
> That's not the case. There are never bias parameters in attention outputs and MLPs for Qwen models. @PIPItian

qwen1.5-32b-gptq的model.safetensors.index.json文件中有bias

**Comment by Ryan-0805** [comment]
> @Ryan-0805 Thank you for describing what you were using. In that case, please use vLLM; the exllama v2 CUDA kernel in auto_gptq uses fp16 for matmul accumulate which could be numerically instable depending on the usecase.感谢您描述您所使用的内容。在这种情况下，请使用vLLM； auto_gptq 中的 exllama v2 CUDA 内核使用 fp16 进行 matmul 累加，这可能在数值上不稳定，具体取决于用例。

谢谢您的解惑，我通过将torch降低至2.2.1版本，以及更新optimum库到最新，可以使用transformers运行Qwen2.5-72B-Instruct-GPTQ

**Comment by jklj077** [comment]
@PIPItian 

It's true that there are never bias parameters in attention outputs and MLPs for Qwen models. For historical reasons, `auto_gptq` includes bias parameters in quantized checkpoints, but for Qwen models, there are all zero vectors, which is the case for Qwen1.5 and Qwen2. However, newer versions of `transformers` will complain about the extra bias parameters (a warning that can be safely ignored but annoying).

For Qwen2.5 GPTQ checkpoints, the bias parameters are not included anymore. It can trigger [an issue](https://www.github.com/huggingface/optimum/pull/1827) in older versions of `optimum`, which forcefully includes the bias, which are initialized as zero vectors by `auto_gptq` but then randomly initialized by `transformers`. In such case, ensure `optimum>1.20.0`.

Nonetheless, inf/nan can still happen for `transformers`+`auto_gptq` even with the proper version of `optimum`. Without more information, numerical instability is the common case if one follows the readme and install the latest version of `transformers`.

**Comment by gg22mm** [comment]
这个问题就没有明确的解决吗~~
