### ISSUE TITLE
[Bug]: hugging face transformers使用长文本推理时报错

### ISSUE THREAD

**Issue by allen20200111** [QwenLM/Qwen2.5#953]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-7B-Instruct

### What is the scenario where the problem happened?

使用transformers推理

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

python: Python 3.10
Ubuntu 22.04
GPUs: 1 x NVIDIA A800
CUDA compiler:  12.4
PyTorch:2.3.1

### Log output

```shell
This is a friendly reminder - the current text generation call will exceed the model's predefined maximum length (32768). Depending on the model, you may observe exceptions, performance degradation, or nothing at all.
generated_ids:  1
```

### Description

在config.json中已经配置文件已经注明了Yarn，还是提示超出范围, 请问什么原因呢？如何解决此问题
{
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  **"rope_scaling": {
    "factor": 4.0,
    "original_max_position_embeddings": 32768,
    "type": "yarn"
  },**
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "rms_norm_eps": 1e-06,
  "rope_theta": 1000000.0,
  "sliding_window": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.43.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

**Comment by jklj077** [comment]
Hi, I don't think transformers support YaRN. Please use vLLM.
