### ISSUE TITLE
[Question]: Can I use the QWEN2.5 model to generate sentence vectors?

### ISSUE THREAD

**Issue by trundleyrg** [QwenLM/Qwen2.5#956]
### Has this been raised before?

- [X] I have checked [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.
- [X] I confirm that this is not a bug report, a feature request, or a badcase.

### Description

Can I use the QWEN2.5 model to generate sentence vectors?

**Comment by jklj077** [comment]
Hi, Qwen2.5 models are not supposed to be directly used as embedding models. Their primary purpose is text generation.

**Comment by LianghuiGuo** [comment]
I met same question. Did you solve it ?TKS

**Comment by trundleyrg** [comment]
> I met same question. Did you solve it ?TKS

 Qwen2.5 models are not supposed to be directly used as embedding models. Because the output of the model is the probability distribution of the next word.
